### let the challenge begin

We will ipip install kaggle and since I have already created a kaggle API key, we will use the same %env to use that key. 
Using that key, we are going to download our data.

In [2]:
#
!pip install kaggle

Requirement already satisfied: kaggle in /home/mishraka/anaconda3/lib/python3.7/site-packages (1.5.1.1)
Requirement already satisfied: certifi in /home/mishraka/anaconda3/lib/python3.7/site-packages (from kaggle) (2018.11.29)
Requirement already satisfied: six>=1.10 in /home/mishraka/anaconda3/lib/python3.7/site-packages (from kaggle) (1.11.0)
Requirement already satisfied: requests in /home/mishraka/anaconda3/lib/python3.7/site-packages (from kaggle) (2.19.1)
Requirement already satisfied: urllib3<1.23.0,>=1.15 in /home/mishraka/anaconda3/lib/python3.7/site-packages (from kaggle) (1.22)
Requirement already satisfied: python-slugify in /home/mishraka/anaconda3/lib/python3.7/site-packages (from kaggle) (2.0.1)
Requirement already satisfied: python-dateutil in /home/mishraka/anaconda3/lib/python3.7/site-packages (from kaggle) (2.7.3)
Requirement already satisfied: tqdm in /home/mishraka/anaconda3/lib/python3.7/site-packages (from kaggle) (4.26.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/mishraka/anaconda3/lib/python3.7/site-packages (from requests->kaggle) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in /home/mishraka/anaconda3/lib/python3.7/site-packages (from requests->kaggle) (2.7)
Requirement already satisfied: Unidecode>=0.04.16 in /home/mishraka/anaconda3/lib/python3.7/site-packages (from python-slugify->kaggle) (1.0.23)

In [3]:
#environment reference for the kaggle api key
%env KAGGLE_CONFIG_DIR=/home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/Advanced_Regression_Week3/fma_metadata/FMS_Data_for_Logistic_regression

env: KAGGLE_CONFIG_DIR=/home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/Advanced_Regression_Week3/fma_metadata/FMS_Data_for_Logistic_regression

In [4]:
#download the data
!kaggle competitions download -c ds1-predictive-modeling-challenge

sample_submission.csv: Skipping, found more recently modified local copy (use --force to force download)
test_features.csv.zip: Skipping, found more recently modified local copy (use --force to force download)
train_labels.csv.zip: Skipping, found more recently modified local copy (use --force to force download)
train_features.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

In [5]:
import pandas as pd
!unzip train_features.csv.zip

Archive:  train_features.csv.zip
replace train_features.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: ^C

In [31]:
pd.set_option('display.max_columns', None)
df_train_features = pd.read_csv('/home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/kaggle_competition/train_features.csv')
df_train_features.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,scheme_name,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,Lake Nyasa,Mnyusi B,Iringa,11,5,Ludewa,Mundindi,109,True,GeoData Consultants Ltd,VWC,Roman,False,1999,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,Lake Victoria,Nyamara,Mara,20,2,Serengeti,Natta,280,NaN,GeoData Consultants Ltd,Other,NaN,True,2010,gravity,gravity,gravity,wug,user-group,never pay,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,Pangani,Majengo,Manyara,21,4,Simanjiro,Ngorika,250,True,GeoData Consultants Ltd,VWC,Nyumba ya mungu pipe scheme,True,2009,gravity,gravity,gravity,vwc,user-group,pay per bucket,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,Mahakamani,Mtwara,90,63,Nanyumbu,Nanyumbu,58,True,GeoData Consultants Ltd,VWC,NaN,True,1986,submersible,submersible,submersible,vwc,user-group,never pay,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,Lake Victoria,Kyanyamisa,Kagera,18,1,Karagwe,Nyakasimbi,0,True,GeoData Consultants Ltd,NaN,NaN,True,0,gravity,gravity,gravity,other,other,never pay,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe

In [32]:
df_train_features.columns

Index(['id', 'amount_tsh', 'date_recorded', 'funder', 'gps_height',
       'installer', 'longitude', 'latitude', 'wpt_name', 'num_private',
       'basin', 'subvillage', 'region', 'region_code', 'district_code', 'lga',
       'ward', 'population', 'public_meeting', 'recorded_by',
       'scheme_management', 'scheme_name', 'permit', 'construction_year',
       'extraction_type', 'extraction_type_group', 'extraction_type_class',
       'management', 'management_group', 'payment', 'payment_type',
       'water_quality', 'quality_group', 'quantity', 'quantity_group',
       'source', 'source_type', 'source_class', 'waterpoint_type',
       'waterpoint_type_group'],
      dtype='object')

In [33]:
df_train_labels = pd.read_csv('/home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/kaggle_competition/train_labels.csv')

In [34]:
df_train_labels.head()

      id    status_group
0  69572      functional
1   8776      functional
2  34310      functional
3  67743  non functional
4  19728      functional

In [10]:
df_train_labels.columns

Index(['id', 'status_group'], dtype='object')

In [11]:
df_train_features.shape

(59400, 40)

In [12]:
df_train_labels.shape

(59400, 2)

## majority Class Baseline

In [13]:
import numpy as np
majority_class = df_train_labels['status_group'].mode()[0]
#print(majority_class)

y_pred = np.full(shape=df_train_labels['status_group'].shape, fill_value=majority_class)

In [14]:
df_train_labels.status_group.shape, y_pred.shape

((59400,), (59400,))

In [15]:
all(y_pred==majority_class)

True

In [16]:
from sklearn.metrics import accuracy_score 
accuracy_score(df_train_labels['status_group'], y_pred)

0.543080808080808

In [17]:
submission_df = pd.DataFrame(y_pred, columns=['status_group_pred'])

In [18]:
submission_df.head()

  status_group_pred
0        functional
1        functional
2        functional
3        functional
4        functional

In [19]:
df_train_labels.head()

      id    status_group
0  69572      functional
1   8776      functional
2  34310      functional
3  67743  non functional
4  19728      functional

In [20]:
submission_baseline = pd.concat([df_train_labels, submission_df], axis=1)

In [21]:
submission_baseline.head()

      id    status_group status_group_pred
0  69572      functional        functional
1   8776      functional        functional
2  34310      functional        functional
3  67743  non functional        functional
4  19728      functional        functional

In [22]:
submission_baseline = submission_baseline.drop(columns='status_group')

In [23]:
submission_baseline.head()

      id status_group_pred
0  69572        functional
1   8776        functional
2  34310        functional
3  67743        functional
4  19728        functional

In [24]:
submission_baseline.to_csv('/home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/kaggle_competition/submission_baseline.csv')

### Class imbalance

In [25]:
df_train_labels['status_group'].value_counts()

functional                 32259
non functional             22824
functional needs repair     4317
Name: status_group, dtype: int64

In [26]:
df_train_labels['status_group'].value_counts(normalize=True)

functional                 0.543081
non functional             0.384242
functional needs repair    0.072677
Name: status_group, dtype: float64

In [27]:
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.metrics import accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression
from mlxtend.plotting import plot_decision_regions


#let's import the warning before running any sophisticated methods
import warnings
from sklearn.exceptions import DataConversionWarning
warnings.filterwarnings(action='ignore', category=DataConversionWarning)

In [28]:
import warnings
from sklearn.exceptions import DataConversionWarning
warnings.filterwarnings(action='ignore', category=DataConversionWarning)

#### How about printing our classification report

In [29]:
print(classification_report(df_train_labels['status_group'], y_pred) )

/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

                         precision    recall  f1-score   support

             functional       0.54      1.00      0.70     32259
functional needs repair       0.00      0.00      0.00      4317
         non functional       0.00      0.00      0.00     22824

              micro avg       0.54      0.54      0.54     59400
              macro avg       0.18      0.33      0.23     59400
           weighted avg       0.29      0.54      0.38     59400

Looking at the above report, it's a pretty bad prediction and recall.

In [30]:
sample_submission_df.head()

NameError: name 'sample_submission_df' is not defined

In [147]:
!kaggle competitions submit -c ds1-predictive-modeling-challenge -f /home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/kaggle_competition/submission_baseline.csv -m "testing submission command"

100%|███████████████████████████████████████| 1.28M/1.28M [00:02<00:00, 512kB/s]
Successfully submitted to DS1 Predictive Modeling Challenge

### Let's consider running a logistic regression only with numeric values

In [35]:
pd.set_option('display.max_columns', None)
df_train_features.head(5)

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,scheme_name,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,Lake Nyasa,Mnyusi B,Iringa,11,5,Ludewa,Mundindi,109,True,GeoData Consultants Ltd,VWC,Roman,False,1999,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,Lake Victoria,Nyamara,Mara,20,2,Serengeti,Natta,280,NaN,GeoData Consultants Ltd,Other,NaN,True,2010,gravity,gravity,gravity,wug,user-group,never pay,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,Pangani,Majengo,Manyara,21,4,Simanjiro,Ngorika,250,True,GeoData Consultants Ltd,VWC,Nyumba ya mungu pipe scheme,True,2009,gravity,gravity,gravity,vwc,user-group,pay per bucket,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,Mahakamani,Mtwara,90,63,Nanyumbu,Nanyumbu,58,True,GeoData Consultants Ltd,VWC,NaN,True,1986,submersible,submersible,submersible,vwc,user-group,never pay,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,Lake Victoria,Kyanyamisa,Kagera,18,1,Karagwe,Nyakasimbi,0,True,GeoData Consultants Ltd,NaN,NaN,True,0,gravity,gravity,gravity,other,other,never pay,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe

In [36]:
df_train_features.shape

(59400, 40)

In [74]:
df_train_features.head(-5)

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322e+00,none,0,Lake Nyasa,Mnyusi B,Iringa,11,5,Ludewa,Mundindi,109,True,GeoData Consultants Ltd,VWC,False,1999,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466e+00,Zahanati,0,Lake Victoria,Nyamara,Mara,20,2,Serengeti,Natta,280,True,GeoData Consultants Ltd,Other,True,2010,gravity,gravity,gravity,wug,user-group,never pay,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329e+00,Kwa Mahundi,0,Pangani,Majengo,Manyara,21,4,Simanjiro,Ngorika,250,True,GeoData Consultants Ltd,VWC,True,2009,gravity,gravity,gravity,vwc,user-group,pay per bucket,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-1.115530e+01,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,Mahakamani,Mtwara,90,63,Nanyumbu,Nanyumbu,58,True,GeoData Consultants Ltd,VWC,True,1986,submersible,submersible,submersible,vwc,user-group,never pay,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359e+00,Shuleni,0,Lake Victoria,Kyanyamisa,Kagera,18,1,Karagwe,Nyakasimbi,0,True,GeoData Consultants Ltd,VWC,True,0,gravity,gravity,gravity,other,other,never pay,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
5,9944,20.0,2011-03-13,Mkinga Distric Coun,0,DWE,39.172796,-4.765587e+00,Tajiri,0,Pangani,Moa/Mwereme,Tanga,4,8,Mkinga,Moa,1,True,GeoData Consultants Ltd,VWC,True,2009,submersible,submersible,submersible,vwc,user-group,pay per bucket,per bucket,salty,salty,enough,enough,other,other,unknown,communal standpipe multiple,communal standpipe
6,19816,0.0,2012-10-01,Dwsp,0,DWSP,33.362410,-3.766365e+00,Kwa Ngomho,0,Internal,Ishinabulandi,Shinyanga,17,3,Shinyanga Rural,Samuye,0,True,GeoData Consultants Ltd,VWC,True,0,swn 80,swn 80,handpump,vwc,user-group,never pay,never pay,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
7,54551,0.0,2012-10-09,Rwssp,0,DWE,32.620617,-4.226198e+00,Tushirikiane,0,Lake Tanganyika,Nyawishi Center,Shinyanga,17,3,Kahama,Chambo,0,True,GeoData Consultants Ltd,VWC,True,0,nira/tanira,nira/tanira,handpump,wug,user-group,unknown,unknown,milky,milky,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
8,53934,0.0,2012-11-03,Wateraid,0,Water Aid,32.711100,-5.146712e+00,Kwa Ramadhan Musa,0,Lake Tanganyika,Imalauduki,Tabora,14,6,Tabora Urban,Itetemia,0,True,GeoData Consultants Ltd,VWC,True,0,india mark ii,india mark ii,handpump,vwc,user-group,never pay,never pay,salty,salty,seasonal,seasonal,machine dbh,borehole,groundwater,hand pump,hand pump
9,46144,0.0,2011-08-03,Isingiro Ho,0,Artisan,30.626991,-1.257051e+00,Kwapeto,0,Lake Victoria,Mkonomre,Kagera,18,1,Karagwe,Kaisho,0,True,GeoData Consultants Ltd,VWC,True,0,nira/tanira,nira/tanira,handpump,vwc,user-group,never pay,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
10,49056,0.0,2011-02-20,Private,62,Private,39.209518,-7.034139e+00,Mzee Hokororo,0,Wami / Ruvu,Mizugo,Pwani,60,43,Mkuranga,Tambani,345,True,GeoData Consultants Ltd,Private operator,False,2011,submersible,submersible,submersible,private operator,commercial,never pay,never pay,salty,salty,enough,enough,machine dbh,borehole,groundwater,other,other
11,50409,200.0,2013-02-18,Danida,1062,DANIDA,35.770258,-1.057417e+01,Kwa Alid Nchimbi,0,Lake Nyasa,Ngondombwito,Ruvuma,10,5,Namtumbo,Msindo,250,True,GeoData Consultants Ltd,WUG,False,1987,swn 80,swn 80,handpump,wug,user-group,pay when scheme fails,on failure,soft,good,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump
12,36957,0.0,2012-10-14,World Vision,0,World vision,33.798106,-3.290194e+00,Pamba,0,Internal,Nkilifa,Shinyanga,17,2,Maswa,Busilili,0,True,GeoData Consultants Ltd,WUG,False,0,nira/tanira,nira/tanira,handpump,wug,user-group,other,other,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
13,50495,0.0,2013-03-15,Lawatefuka Water Supply,1368,Lawatefuka water sup,37.092574,-3.181783e+00,Kwa John Izack Mmari,0,Pangani,Omarini,Kilimanjaro,3,7,Siha,Siha Kaskazini,1,True,GeoData Consultants Ltd,Water Board,True,2009,gravity,gravity,gravity,water board,user-group,pay monthly,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
14,53752,0.0,2012-10-20,Biore,0,WEDECO,34.364073,-3.629333e+00,Mwabasabi,0,Internal,Mwabasabi,Shinyanga,17,6,Meatu,Nkoma,0,True,GeoData Consultants Ltd,WUG,True,0,nira/tanira,nira/tanira,handpump,wug,user-group,never pay,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
15,61848,0.0,2011-08-04,Rudep,1645,DWE,31.444121,-8.274962e+00,Kwa Juvenal Ching'Ombe,0,Lake Tanganyika,Tunzi,Rukwa,15,2,Sumbawanga Rural,Mkowe,200,True,GeoData Consultants Ltd,VWC,False,1991,swn 80,swn 80,handpump,vwc,user-group,never pay,never pay,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
16,48451,500.0,2011-07-04,Unicef,1703,DWE,34.642439,-9.106185e+00,Kwa John Mtenzi,0,Rufiji,Kidudumo,Iringa,11,4,Njombe,Mdandu,35,True,GeoData Consultants Ltd,WUA,True,1978,gravity,gravity,gravity,wua,user-group,pay monthly,monthly,soft,good,dry,dry,river,river/lake,surface,communal standpipe,communal standpipe
17,58155,0.0,2011-09-04,Unicef,1656,DWE,34.569266,-9.085515e+00,Kwa Rose Chaula,0,Rufiji,Yeriko,Iringa,11,4,Njombe,Usuka,50,True,GeoData Consultants Ltd,WUA,True,1978,gravity,gravity,gravity,wua,user-group,pay when scheme fails,on failure,soft,good,dry,dry,river,river/lake,surface,communal standpipe,communal standpipe
18,34169,0.0,2011-07-22,Hesawa,1162,DWE,32.920154,-1.947868e+00,Ngomee,0,Lake Victoria,Center,Mwanza,19,1,Ukerewe,Ilangala,1000,True,GeoData Consultants Ltd,VWC,True,1999,other,other,other,vwc,user-group,never pay,never pay,milky,milky,insufficient,insufficient,spring,spring,groundwater,other,other
19,18274,500.0,2011-02-22,Danida,1763,Danid,34.508967,-9.894412e+00,none,0,Lake Nyasa,Manyanya,Iringa,11,5,Ludewa,Mawengi,1,True,GeoData Consultants Ltd,VWC,True,1992,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
20,48375,200.0,2011-02-27,Twe,2216,TWE,34.473430,-9.594990e+00,none,0,Lake Nyasa,Majengo,Iringa,11,4,Njombe,Matola,4,True,GeoData Consultants Ltd,VWC,False,2008,gravity,gravity,gravity,vwc,user-group,pay monthly,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
21,6091,0.0,2013-02-10,Dwsp,0,DWE,0.000000,-2.000000e-08,Muungano,0,Lake Victoria,Ibabachegu,Shinyanga,17,1,Bariadi,Ikungulyabashashi,0,True,GeoData Consultants Ltd,WUG,False,0,swn 80,swn 80,handpump,wug,user-group,unknown,unknown,unknown,unknown,unknown,unknown,shallow well,shallow well,groundwater,hand pump,hand pump
22,58500,0.0,2011-10-04,Unicef,1510,DWE,34.586901,-8.980014e+00,Shuleni,0,Rufiji,Mkanivega,Iringa,11,4,Njombe,Usuka,350,True,GeoData Consultants Ltd,WUA,True,1978,gravity,gravity,gravity,wua,user-group,never pay,never pay,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
23,37862,500.0,2013-11-03,Isf,672,ISF,37.940029,-4.125595e+00,Kinonga,0,Pangani,Mkonga Juu,Kilimanjaro,3,3,Same,Kisiwani,210,True,GeoData Consultants Ltd,Water authority,True,2011,gravity,gravity,gravity,vwc,user-group,pay monthly,monthly,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
24,51058,0.0,2013-01-21,African Development Bank,1645,DWE,29.747066,-4.495568e+00,Kamsasa,0,Lake Tanganyika,Msasa,Kigoma,16,3,Kigoma Rural,Mkigo,156,False,GeoData Consultants Ltd,VWC,True,2009,gravity,gravity,gravity,vwc,user-group,unknown,unknown,soft,good,enough,enough,spring,spring,groundwater,improved spring,improved spring
25,22308,0.0,2013-02-25,Government Of Tanzania,1273,DWE,37.422751,-3.317536e+00,Kwa Tukai,0,Pangani,Kitereni,Kilimanjaro,3,4,Moshi Rural,Kimochi,140,True,GeoData Consultants Ltd,VWC,True,1974,gravity,gravity,gravity,vwc,user-group,unknown,unknown,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
26,55012,500.0,2013-01-16,Sobodo,200,Kilolo Star,39.370777,-9.942532e+00,Ruhoma Primary School,0,Ruvuma / Southern Coast,Shuleni,Lindi,80,23,Lindi Rural,Rutamba,260,False,GeoData Consultants Ltd,VWC,False,2011,india mark ii,india mark ii,handpump,vwc,user-group,pay monthly,monthly,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
27,20145,0.0,2011-07-11,Hesawa,0,DWE,31.104257,-1.735361e+00,Kwawilliam,0,Lake Victoria,Chakahaya,Kagera,18,1,Karagwe,Nyaishozi,0,True,GeoData Consultants Ltd,VWC,True,0,nira/tanira,nira/tanira,handpump,vwc,user-group,never pay,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
28,19685,0.0,2013-03-05,Government Of Tanzania,1443,District council,37.611126,-3.263526e+00,Kwa Kibakaya,0,Pangani,Kiyao,Kilimanjaro,3,1,Rombo,Mengwe Manda,1,True,GeoData Consultants Ltd,Company,True,2000,gravity,gravity,gravity,company,commercial,pay monthly,monthly,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
29,69124,0.0,2013-03-16,Lawatefuka Water Supply,1256,Lawatefuka water sup,37.061688,-3.191989e+00,Kwa Willium Kinda,0,Pangani,Merali,Kilimanjaro,3,7,Siha,Siha Kati,1,True,GeoData Consultants Ltd,Water Board,True,2002,gravity,gravity,gravity,water board,user-group,pay monthly,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59365,8810,0.0,2011-09-04,Unicef,1656,DWE,34.594790,-9.072904e+00,Kwa Yohane Mhanza,0,Rufiji,Kati,Iringa,11,4,Njombe,Usuka,35,True,GeoData Consultants Ltd,WUA,True,1978,gravity,gravity,gravity,wua,user-group,pay when scheme fails,on failure,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
59366,55232,0.0,2013-02-02,Government Of Tanzania,1541,DWE,34.765729,-5.027725e+00,Joshoni,0,Internal,Mungumaho,Singida,13,2,Singida Rural,Puma,200,True,GeoData Consultants Ltd,VWC,True,2000,nira/tanira,nira/tanira,handpump,vwc,user-group,never pay,never pay,soft,good,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump
59367,73019,2000.0,2011-03-09,Government Of Tanzania,1977,Commu,34.338899,-9.565553e+00,none,0,Lake Nyasa,Chunya,Iringa,11,3,Makete,Lupila,0,True,GeoData Consultants Ltd,VWC,False,1976,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59368,61732,0.0,2011-03-08,Dct,0,Gove,35.657558,-6.526272e+00,Mgomwa,0,Rufiji,Mgomwa,Dodoma,1,6,Bahi,Mwitikira,0,True,GeoData Consultants Ltd,VWC,True,0,mono,mono,motorpump,vwc,user-group,pay per bucket,per bucket,soft,good,enough,enough,machine dbh,borehole,groundwater,communal standpipe,communal standpipe
59369,47527,0.0,2011-04-12,Rc Church,0,RC Church,33.670049,-9.001535e+00,Kwa Paval Dinno,0,Lake Nyasa,Mjimwema,Mbeya,12,2,Mbeya Rural,Ulenje,0,False,GeoData Consultants Ltd,VWC,False,0,gravity,gravity,gravity,wug,user-group,pay when scheme fails,on failure,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
59370,14796,200.0,2013-01-29,Government Of Tanzania,1154,DWE,30.058731,-4.902633e+00,Village Office,0,Lake Tanganyika,Mazungwe,Kigoma,16,2,Kasulu,Rusesa,1,True,GeoData Consultants Ltd,VWC,False,0,other,other,other,unknown,unknown,pay monthly,monthly,unknown,unknown,unknown,unknown,unknown,other,unknown,other,other
59371,20387,0.0,2012-10-09,Netherlands,0,DWE,33.586406,-3.040369e+00,Ushirika,0,Lake Victoria,Chambwa,Shinyanga,17,2,Maswa,Kulimi,0,True,GeoData Consultants Ltd,WUG,False,0,nira/tanira,nira/tanira,handpump,wug,user-group,never pay,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
59372,29940,0.0,2012-10-31,Tlc,0,TLC,32.058548,-5.052101e+00,Kwa Mzee Kamanya,0,Lake Tanganyika,Urambo Magharibi,Tabora,14,4,Urambo,Urambo,0,True,GeoData Consultants Ltd,Private operator,True,0,other,other,other,private operator,commercial,pay per bucket,per bucket,salty,salty,insufficient,insufficient,shallow well,shallow well,groundwater,other,other
59373,15233,5000.0,2013-01-30,Rudep,1137,Distri,32.125024,-6.784358e+00,Kwa Kadiega,0,Lake Rukwa,Mapambano,Rukwa,15,1,Mpanda,Ilela,96,True,GeoData Consultants Ltd,VWC,True,1988,india mark ii,india mark ii,handpump,vwc,user-group,pay annually,annually,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
59374,49651,0.0,2012-10-29,Rwssp,0,DWE,0.000000,-2.000000e-08,Nguvu Kazi,0,Lake Victoria,Mwamtani A,Shinyanga,17,1,Bariadi,Sagata,0,True,GeoData Consultants Ltd,WUG,False,0,nira/tanira,nira/tanira,handpump,wug,user-group,other,other,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
59375,50998,40000.0,2011-08-03,Government Of Tanzania,54,DWE,39.046942,-5.061494e+00,Sekondari,0,Pangani,Kwa Nyanji,Tanga,4,4,Tanga,Mzizima,609,True,GeoData Consultants Ltd,VWC,True,2005,gravity,gravity,gravity,vwc,user-group,pay monthly,monthly,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
59376,34716,0.0,2013-02-03,Government Of Tanzania,1581,DWE,34.821039,-5.076258e+00,Nasingo,0,Internal,Hu,Singida,13,2,Singida Rural,Dung'unyi,1,True,GeoData Consultants Ltd,VWC,True,1990,other,other,other,vwc,user-group,unknown,unknown,unknown,unknown,dry,dry,shallow well,shallow well,groundwater,other,other
59377,43986,0.0,2012-10-23,Government Of Tanzania,0,Government,33.437012,-4.423594e+00,Fpct,0,Internal,Hospital,Tabora,14,2,Igunga,Nkinga,0,True,GeoData Consultants Ltd,Water authority,False,0,gravity,gravity,gravity,vwc,user-group,never pay,never pay,soft,good,insufficient,insufficient,dam,dam,surface,communal standpipe multiple,communal standpipe
59378,38067,500.0,2011-03-21,Rc,2101,ACRA,34.620387,-9.358405e+00,Michael Msigwa,0,Rufiji,Igelango,Iringa,11,4,Njombe,Imalinyi,36,True,GeoData Consultants Ltd,VWC,True,2008,gravity,gravity,gravity,wua,user-group,pay monthly,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59379,58255,0.0,2011-07-13,Do,0,DO,31.613284,-1.820226e+00,Coffee Plantati,0,Lake Victoria,Kaluyango,Kagera,18,3,Muleba,Ikondo,0,True,GeoData Consultants Ltd,VWC,True,0,gravity,gravity,gravity,vwc,user-group,never pay,never pay,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59380,30647,6000.0,2011-03-14,Roman,1439,Roman,34.942101,-9.849198e+00,none,0,Lake Nyasa,Mnyusi B,Iringa,11,5,Ludewa,Mundindi,50,True,GeoData Consultants Ltd,VWC,False,1999,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,dry,dry,spring,spring,groundwater,communal standpipe,communal standpipe
59381,67885,0.0,2011-03-16,Mkinga Distric Coun,0,DWE,38.835001,-4.880204e+00,Mijohoroni,0,Pangani,Mtakuja A,Tanga,4,8,Mkinga,Maramba,360,True,GeoData Consultants Ltd,VWC,True,1992,gravity,gravity,gravity,vwc,user-group,never pay,never pay,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
59382,47002,6.0,2013-08-03,Ces(gmbh),1383,DWE,37.454759,-3.323599e+00,Kwa Luka Msaki,0,Pangani,Yamu Juu,Kilimanjaro,3,4,Moshi Rural,Kirua Vunjo Kusini,1,True,GeoData Consultants Ltd,Water Board,True,2008,gravity,gravity,gravity,water board,user-group,pay per bucket,per bucket,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59383,44616,0.0,2013-01-19,World Bank,11,World bank,39.626009,-1.005750e+01,Shuleni,0,Ruvuma / Southern Coast,Mitumbati,Lindi,80,62,Lindi Urban,Jamhuri,800,True,GeoData Consultants Ltd,VWC,True,2008,nira/tanira,nira/tanira,handpump,vwc,user-group,unknown,unknown,soft,good,enough,enough,rainwater harvesting,rainwater harvesting,surface,hand pump,hand pump
59384,72148,0.0,2011-07-10,Concern,0,CONCERN,30.667805,-2.483710e+00,Chamkube,0,Lake Victoria,Songambele,Kagera,18,30,Ngara,Nyamiyaga,0,True,GeoData Consultants Ltd,VWC,False,0,gravity,gravity,gravity,vwc,user-group,never pay,never pay,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
59385,34473,500.0,2012-11-03,Jaica,1327,JAICA CO,33.951681,-2.021854e+00,Kwa Marunda,0,Lake Victoria,Mlimani,Mara,20,4,Bunda,Mcharo,200,True,GeoData Consultants Ltd,WUG,True,2011,afridev,afridev,handpump,wug,user-group,pay monthly,monthly,salty,salty,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
59386,34952,0.0,2011-08-22,Adb,1786,DWE,31.738789,-8.532013e+00,Shule Ya Sekondari Katazi,0,Lake Rukwa,Nduza,Rukwa,15,2,Sumbawanga Rural,Katazi,1000,True,GeoData Consultants Ltd,VWC,False,2009,india mark ii,india mark ii,handpump,vwc,user-group,never pay,never pay,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
59387,26640,100.0,2013-03-12,0,25,0,39.176480,-6.957098e+00,Kwa Maliba,0,Wami / Ruvu,Mtaa Wa Yangeyange,Dar es Salaam,7,2,Ilala,Msongola,100,True,GeoData Consultants Ltd,WUA,False,2000,submersible,submersible,submersible,wua,user-group,pay per bucket,per bucket,soft,good,enough,enough,machine dbh,borehole,groundwater,communal standpipe,communal standpipe
59388,72559,0.0,2013-01-29,Kidep,1414,DWE,30.692400,-3.593827e+00,Kwa Philipo Kibeba,0,Lake Tanganyika,Kumwambu,Kigoma,16,1,Kibondo,Kibondo Urban,500,True,GeoData Consultants Ltd,VWC,True,1995,gravity,gravity,gravity,vwc,user-group,unknown,unknown,soft,good,insufficient,insufficient,spring,spring,groundwater,improved spring,improved spring
59389,30410,0.0,2011-08-06,Co,783,DWE,30.646486,-7.365418e+00,Sekondari,0,Lake Tanganyika,Itete B,Rukwa,15,3,Nkasi,Kirando,1500,False,GeoData Consultants Ltd,VWC,False,2009,india mark ii,india mark ii,handpump,vwc,user-group,never pay,never pay,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
59390,13677,0.0,2011-08-04,Rudep,1715,DWE,31.370848,-8.258160e+00,Kwa Mzee Atanas,0,Lake Tanganyika,Kitonto,Rukwa,15,2,Sumbawanga Rural,Mkowe,150,True,GeoData Consultants Ltd,VWC,False,1991,swn 80,swn 80,handpump,vwc,user-group,never pay,never pay,soft,good,insufficient,insufficient,machine dbh,borehole,groundwater,hand pump,hand pump
59391,44885,0.0,2013-08-03,Government Of Tanzania,540,Government,38.044070,-4.272218e+00,Kwa,0,Pangani,Maore Kati,Kilimanjaro,3,3,Same,Maore,210,True,GeoData Consultants Ltd,Water authority,True,1967,gravity,gravity,gravity,vwc,user-group,never pay,never pay,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
59392,40607,0.0,2011-04-15,Government Of Tanzania,0,Government,33.009440,-8.520888e+00,Benard Charles,0,Lake Rukwa,Mbuyuni A,Mbeya,12,1,Chunya,Mbuyuni,0,True,GeoData Consultants Ltd,VWC,True,0,gravity,gravity,gravity,vwc,user-group,never pay,never pay,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe

## Let's check the Test file

In [71]:
#import pdandas as pd
df_test_features = pd.read_csv('/home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/kaggle_competition/test_features.csv')

In [72]:
df_test_features.shape

(14358, 40)

In [126]:
df_train_features.columns

Index(['id', 'amount_tsh', 'date_recorded', 'funder', 'gps_height',
       'installer', 'longitude', 'latitude', 'wpt_name', 'num_private',
       'basin', 'subvillage', 'region', 'region_code', 'district_code', 'lga',
       'ward', 'population', 'public_meeting', 'recorded_by',
       'scheme_management', 'permit', 'construction_year', 'extraction_type',
       'extraction_type_group', 'extraction_type_class', 'management',
       'management_group', 'payment', 'payment_type', 'water_quality',
       'quality_group', 'quantity', 'quantity_group', 'source', 'source_type',
       'source_class', 'waterpoint_type', 'waterpoint_type_group'],
      dtype='object')

### merge Train and test sets
it's the same formula, just don't mention axis=1
The last row of our df_train_features dataset is 59394

In [75]:
#Let's merge train and test
full_df = pd.concat([df_train_features, df_test_features])

/home/mishraka/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

In [76]:
full_df.shape

(73758, 40)

In [77]:
59400 + 14358

73758

In [127]:
full_df.columns

Index(['amount_tsh', 'basin', 'construction_year', 'date_recorded',
       'district_code', 'extraction_type', 'extraction_type_class',
       'extraction_type_group', 'funder', 'gps_height', 'id', 'installer',
       'latitude', 'lga', 'longitude', 'management', 'management_group',
       'num_private', 'payment', 'payment_type', 'permit', 'population',
       'public_meeting', 'quality_group', 'quantity', 'quantity_group',
       'recorded_by', 'region', 'region_code', 'scheme_management', 'source',
       'source_class', 'source_type', 'subvillage', 'ward', 'water_quality',
       'waterpoint_type', 'waterpoint_type_group', 'wpt_name'],
      dtype='object')

In [79]:
#let's drop the columns with 28k nans 
full_df = full_df.drop(columns='scheme_name')

i'll take care of the misisng values in other columns now

In [80]:
#data['Native Country'] = data['Native Country'].fillna(data['Native Country'].mode()[0])
full_df['funder'] = full_df['funder'].fillna(full_df['funder'].mode()[0])

In [81]:
full_df['installer'] = full_df['installer'].fillna(full_df['installer'].mode()[0])

In [82]:
full_df['subvillage'] = full_df['subvillage'].fillna(full_df['subvillage'].mode()[0])

In [83]:
full_df['public_meeting'] = full_df['public_meeting'].fillna(full_df['public_meeting'].mode()[0])

In [84]:
full_df['scheme_management'] = full_df['scheme_management'].fillna(full_df['scheme_management'].mode()[0])

In [85]:
full_df['permit'] = full_df['permit'].fillna(full_df['permit'].mode()[0])

In [86]:
full_df.isna().sum()

amount_tsh               0
basin                    0
construction_year        0
date_recorded            0
district_code            0
extraction_type          0
extraction_type_class    0
extraction_type_group    0
funder                   0
gps_height               0
id                       0
installer                0
latitude                 0
lga                      0
longitude                0
management               0
management_group         0
num_private              0
payment                  0
payment_type             0
permit                   0
population               0
public_meeting           0
quality_group            0
quantity                 0
quantity_group           0
recorded_by              0
region                   0
region_code              0
scheme_management        0
source                   0
source_class             0
source_type              0
subvillage               0
ward                     0
water_quality            0
waterpoint_type          0
waterpoint_type_group    0
wpt_name                 0
dtype: int64

### What if we merge the features dataset with the labels df

In [46]:
#merged_df =pd.concat([df_train_labels, df_train_features], axis=1)

In [89]:
#merged_df.head(20)

In [49]:


#main_df = merged_df.loc[:, ~merged_df.columns.duplicated()]

In [88]:
#main_df.head()

In [87]:
#main_df.sort_values(by=['date_recorded'], ascending=True)

### Now since we took care of our missing values, let's get our X matrix and y first

In [99]:
#split the data back
X_cleaned = full_df[:-14358]
X_test_cleaned = full_df[-14358:]
y = df_train_labels['status_group']

In [100]:
X_cleaned.shape, X_test_cleaned.shape, y.shape

((59400, 39), (14358, 39), (59400,))

In [101]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_cleaned, y, test_size=0.25, random_state=42, shuffle=True)

In [102]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((44550, 39), (14850, 39), (44550,), (14850,))

In [103]:
X_train.head()

,amount_tsh,basin,construction_year,date_recorded,district_code,extraction_type,extraction_type_class,extraction_type_group,funder,gps_height,id,installer,latitude,lga,longitude,management,management_group,num_private,payment,payment_type,permit,population,public_meeting,quality_group,quantity,quantity_group,recorded_by,region,region_code,scheme_management,source,source_class,source_type,subvillage,ward,water_quality,waterpoint_type,waterpoint_type_group,wpt_name
24947,20.0,Wami / Ruvu,1972,2011-03-08,1,ksb,submersible,submersible,Government Of Tanzania,330,33935,Ce,-6.087137e+00,Bagamoyo,38.123839,vwc,user-group,0,pay per bucket,per bucket,True,80,True,salty,insufficient,insufficient,GeoData Consultants Ltd,Pwani,6,VWC,machine dbh,groundwater,borehole,Kilangawageni,Mbwewe,salty,communal standpipe,communal standpipe,Ccm
22630,0.0,Lake Victoria,0,2013-02-16,1,nira/tanira,handpump,nira/tanira,Dwsp,0,49654,DWE,-2.000000e-08,Magu,0.000000,wug,user-group,0,unknown,unknown,False,0,True,good,enough,enough,GeoData Consultants Ltd,Mwanza,17,WUG,shallow well,groundwater,shallow well,Mwamahala,Nkungulu,soft,hand pump,hand pump,Mwamahonza
13789,0.0,Lake Victoria,0,2011-08-13,4,india mark ii,handpump,india mark ii,Dasip,0,39287,DASIP,-2.814100e+00,Kwimba,33.312321,vwc,user-group,0,never pay,never pay,True,0,True,good,enough,enough,GeoData Consultants Ltd,Mwanza,19,VWC,machine dbh,groundwater,borehole,Chanongu,Wala,soft,hand pump,hand pump,Chanongu
15697,0.0,Internal,2010,2013-01-20,4,gravity,gravity,gravity,Government Of Tanzania,1542,60510,GOVERNMENT,-4.842093e+00,Singida Urban,34.783049,wua,user-group,0,never pay,never pay,True,23,True,good,seasonal,seasonal,GeoData Consultants Ltd,Singida,13,WUA,rainwater harvesting,surface,rainwater harvesting,Mungumaji,Mungumaji,soft,communal standpipe,communal standpipe,Zahanati
22613,0.0,Lake Nyasa,2013,2013-09-03,3,gravity,gravity,gravity,World Bank,523,24259,Government,-1.070733e+01,Mbinga,34.660944,vwc,user-group,0,unknown,unknown,True,1,True,good,dry,dry,GeoData Consultants Ltd,Ruvuma,10,VWC,spring,groundwater,spring,Tumba,Mbaha,soft,communal standpipe,communal standpipe,Kwa Mzee Charles

In [58]:
y_train.head()

24947    non functional
22630        functional
13789        functional
15697        functional
22613    non functional
Name: status_group, dtype: object

Let's try another baseline with only numeric features

In [104]:
X_train.dtypes

amount_tsh               float64
basin                     object
construction_year          int64
date_recorded             object
district_code              int64
extraction_type           object
extraction_type_class     object
extraction_type_group     object
funder                    object
gps_height                 int64
id                         int64
installer                 object
latitude                 float64
lga                       object
longitude                float64
management                object
management_group          object
num_private                int64
payment                   object
payment_type              object
permit                      bool
population                 int64
public_meeting              bool
quality_group             object
quantity                  object
quantity_group            object
recorded_by               object
region                    object
region_code                int64
scheme_management         object
source                    object
source_class              object
source_type               object
subvillage                object
ward                      object
water_quality             object
waterpoint_type           object
waterpoint_type_group     object
wpt_name                  object
dtype: object

In [105]:
X_train_numeric = X_train.select_dtypes(np.number)

In [106]:
X_test_numeric = X_test.select_dtypes(np.number)

In [107]:
#let's see how our model does here

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train_numeric, y_train)
y_pred = model.predict(X_test_numeric)
accuracy_score(y_test, y_pred)

/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

0.5546127946127946

In [108]:
X_train_numeric.head()

,amount_tsh,construction_year,district_code,gps_height,id,latitude,longitude,num_private,population,region_code
24947,20.0,1972,1,330,33935,-6.087137e+00,38.123839,0,80,6
22630,0.0,0,1,0,49654,-2.000000e-08,0.000000,0,0,17
13789,0.0,0,4,0,39287,-2.814100e+00,33.312321,0,0,19
15697,0.0,2010,4,1542,60510,-4.842093e+00,34.783049,0,23,13
22613,0.0,2013,3,523,24259,-1.070733e+01,34.660944,0,1,10

In [63]:
!pip install category_encoders

Requirement already satisfied: category_encoders in /home/mishraka/anaconda3/lib/python3.7/site-packages (1.3.0)
Requirement already satisfied: statsmodels>=0.6.1 in /home/mishraka/anaconda3/lib/python3.7/site-packages (from category_encoders) (0.9.0)
Requirement already satisfied: patsy>=0.4.1 in /home/mishraka/anaconda3/lib/python3.7/site-packages (from category_encoders) (0.5.0)
Requirement already satisfied: scipy>=0.17.0 in /home/mishraka/anaconda3/lib/python3.7/site-packages (from category_encoders) (1.1.0)
Requirement already satisfied: pandas>=0.20.1 in /home/mishraka/anaconda3/lib/python3.7/site-packages (from category_encoders) (0.23.4)
Requirement already satisfied: scikit-learn>=0.17.1 in /home/mishraka/anaconda3/lib/python3.7/site-packages (from category_encoders) (0.20.2)
Requirement already satisfied: numpy>=1.11.1 in /home/mishraka/anaconda3/lib/python3.7/site-packages (from category_encoders) (1.15.4)
Requirement already satisfied: six in /home/mishraka/anaconda3/lib/python3.7/site-packages (from patsy>=0.4.1->category_encoders) (1.11.0)
Requirement already satisfied: python-dateutil>=2.5.0 in /home/mishraka/anaconda3/lib/python3.7/site-packages (from pandas>=0.20.1->category_encoders) (2.7.3)
Requirement already satisfied: pytz>=2011k in /home/mishraka/anaconda3/lib/python3.7/site-packages (from pandas>=0.20.1->category_encoders) (2018.5)

In [109]:
from sklearn.preprocessing import LabelEncoder
def dummyEncode(df):
        columnsToEncode = list(df.select_dtypes(include=['category','object']))
        le = LabelEncoder()
        for feature in columnsToEncode:
            try:
                df[feature] = le.fit_transform(df[feature])
            except:
                print('Error encoding '+feature)
        return df

In [110]:
cat_coded_df = dummyEncode(X_cleaned)

/home/mishraka/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [111]:
cat_coded_df.head()

,amount_tsh,basin,construction_year,date_recorded,district_code,extraction_type,extraction_type_class,extraction_type_group,funder,gps_height,id,installer,latitude,lga,longitude,management,management_group,num_private,payment,payment_type,permit,population,public_meeting,quality_group,quantity,quantity_group,recorded_by,region,region_code,scheme_management,source,source_class,source_type,subvillage,ward,water_quality,waterpoint_type,waterpoint_type_group,wpt_name
0,6000.0,1,1999,47,5,3,0,1,1369,1390,69572,1518,-9.856322,51,34.938093,7,4,0,2,0,False,109,True,2,1,1,0,3,11,7,8,0,6,11807,1426,6,1,1,37399
1,0.0,4,2010,309,2,3,0,1,469,1399,8776,545,-2.147466,103,34.698766,11,4,0,0,2,True,280,True,2,2,2,0,9,20,2,5,1,3,15838,1576,6,1,1,37195
2,25.0,5,2009,300,4,3,0,1,825,686,34310,2048,-3.821329,108,37.460664,7,4,0,4,5,True,250,True,2,1,1,0,8,21,7,0,1,1,9074,1624,6,2,1,14572
3,0.0,7,1986,272,63,14,5,10,1741,263,67743,1852,-11.155298,87,38.486161,7,4,0,0,2,True,58,True,2,0,0,0,12,90,7,3,0,0,8982,1571,6,2,1,37285
4,0.0,4,0,104,1,3,0,1,20,0,19728,119,-1.825359,26,31.130847,1,1,0,0,2,True,0,True,2,3,3,0,4,18,7,5,1,3,7698,1687,6,1,1,35529

In [192]:
X_cleaned = dummyEncode(X_test_cleaned)

/home/mishraka/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [193]:
X_cleaned.head()

,amount_tsh,basin,construction_year,date_recorded,district_code,extraction_type,extraction_type_class,extraction_type_group,funder,gps_height,id,installer,latitude,lga,longitude,management,management_group,num_private,payment,payment_type,permit,population,public_meeting,quality_group,quantity,quantity_group,recorded_by,region,region_code,scheme_management,source,source_class,source_type,subvillage,ward,water_quality,waterpoint_type,waterpoint_type_group,wpt_name
0,0.0,0,2012,255,3,9,3,6,174,1996,50785,214,-4.059696,62,35.290799,3,2,0,0,2,True,321,True,2,3,3,0,8,21,2,5,1,3,3807,16,6,6,5,633
1,0.0,5,2000,255,2,3,0,1,247,1569,51630,219,-3.309214,0,36.656709,7,4,0,0,2,True,300,True,2,2,2,0,0,2,6,8,0,6,2634,642,6,1,1,1727
2,0.0,0,2010,252,2,9,3,6,247,1567,17168,219,-5.004344,108,34.767863,7,4,0,0,2,True,500,True,2,2,2,0,18,13,6,5,1,3,5271,1659,6,6,5,9483
3,0.0,7,1987,242,43,9,3,6,220,267,45559,259,-9.418672,48,38.058046,7,4,0,6,6,True,250,True,2,0,0,0,7,80,6,7,0,5,2710,1178,6,6,5,5467
4,500.0,7,2000,306,3,3,0,1,72,1260,49871,75,-10.950412,60,35.006123,9,4,0,3,1,True,60,True,2,1,1,0,16,10,9,8,0,6,3442,1061,6,1,1,5573

In [115]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(cat_coded_df, y, test_size=0.25, random_state=42, shuffle=True)

In [195]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='newton-cg', multi_class='multinomial')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy_score(y_test, y_pred)

/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)

0.6408754208754208

In [196]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

pipeline = make_pipeline(StandardScaler(), 
                        LogisticRegression(solver='newton-cg', multi_class='multinomial'))

pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_cleaned)

In [197]:
accuracy_score(y_test, y_pred)

ValueError: Found input variables with inconsistent numbers of samples: [14850, 14358]

In [122]:
y_pred

array(['non functional', 'non functional', 'functional', ...,
       'functional', 'functional', 'non functional'], dtype=object)

In [140]:
X_test.shape, y_pred.shape

((14850, 39), (14850,))

In [178]:
submission_second_file = pd.DataFrame(X_test.id.values, columns=['id'])

In [179]:
submission_second_file.head()

      id
0  37098
1  14530
2  62607
3  46053
4  47083

In [177]:
submission_second_file.id.values[0:10]

array([37098, 14530, 62607, 46053, 47083, 12465, 12921, 14606,  9417,
       71095])

In [144]:
submission_second_file.isna().sum()

id    0
dtype: int64

In [152]:
df_train_labels.head()

      id    status_group
0  69572      functional
1   8776      functional
2  34310      functional
3  67743  non functional
4  19728      functional

In [158]:
y = pd.DataFrame(y_pred, columns=['status_group'])

In [164]:
y.shape

(14850, 1)

In [182]:
submission_second.head()

      id    status_group
0  37098  non functional
1  14530  non functional
2  62607      functional
3  46053      functional
4  47083      functional

In [180]:
submission_second = pd.concat([submission_second_file, y], axis=1)

In [181]:
submission_second.shape

(14850, 2)

In [187]:
submission_second.to_csv('/home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/kaggle_competition/submission_second.csv', index=False)

In [191]:
!kaggle competitions submit -c ds1-predictive-modeling-challenge -f /home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/kaggle_competition/submission_second.csv -m "second submission command"

100%|█████████████████████████████████████████| 262k/262k [00:01<00:00, 175kB/s]
Successfully submitted to DS1 Predictive Modeling Challenge

In [188]:
df = pd.read_csv("/home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/kaggle_competition/submission_second.csv")

In [190]:
df.head()

      id    status_group
0  37098  non functional
1  14530  non functional
2  62607      functional
3  46053      functional
4  47083      functional

In [ ]:
# #let's use OneHot Encoding before we try standard scaler
# from sklearn.pipeline import make_pipeline
# import catergory_encoders as ce
# pipeline = make_pipeline(
#     ce.OneHotEncoder(use_cat_names=True), 
#                         LogisticRegression(solver='newton-cg', multi_class='multinomial'))

# pipeline.fit(X_train, y_train)
# y_pred = pipeline.predict(X_test)
# accuracy_score(y_test, y_pred)