### let the challenge begin

We will ipip install kaggle and since I have already created a kaggle API key, we will use the same %env to use that key. 
Using that key, we are going to download our data.

In [122]:
#
!pip install kaggle

Requirement already satisfied: kaggle in /home/mishraka/anaconda3/lib/python3.7/site-packages (1.5.1.1)
Requirement already satisfied: urllib3<1.23.0,>=1.15 in /home/mishraka/anaconda3/lib/python3.7/site-packages (from kaggle) (1.22)
Requirement already satisfied: requests in /home/mishraka/anaconda3/lib/python3.7/site-packages (from kaggle) (2.19.1)
Requirement already satisfied: python-slugify in /home/mishraka/anaconda3/lib/python3.7/site-packages (from kaggle) (2.0.1)
Requirement already satisfied: tqdm in /home/mishraka/anaconda3/lib/python3.7/site-packages (from kaggle) (4.26.0)
Requirement already satisfied: six>=1.10 in /home/mishraka/anaconda3/lib/python3.7/site-packages (from kaggle) (1.11.0)
Requirement already satisfied: certifi in /home/mishraka/anaconda3/lib/python3.7/site-packages (from kaggle) (2018.11.29)
Requirement already satisfied: python-dateutil in /home/mishraka/anaconda3/lib/python3.7/site-packages (from kaggle) (2.7.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/mishraka/anaconda3/lib/python3.7/site-packages (from requests->kaggle) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in /home/mishraka/anaconda3/lib/python3.7/site-packages (from requests->kaggle) (2.7)
Requirement already satisfied: Unidecode>=0.04.16 in /home/mishraka/anaconda3/lib/python3.7/site-packages (from python-slugify->kaggle) (1.0.23)

In [125]:
#environment reference for the kaggle api key
%env KAGGLE_CONFIG_DIR=/home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/Advanced_Regression_Week3/fma_metadata/FMS_Data_for_Logistic_regression

env: KAGGLE_CONFIG_DIR=/home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/Advanced_Regression_Week3/fma_metadata/FMS_Data_for_Logistic_regression

In [126]:
#download the data
!kaggle competitions download -c ds1-predictive-modeling-challenge

sample_submission.csv: Skipping, found more recently modified local copy (use --force to force download)
test_features.csv.zip: Skipping, found more recently modified local copy (use --force to force download)
train_labels.csv.zip: Skipping, found more recently modified local copy (use --force to force download)
train_features.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

In [127]:
import pandas as pd
!unzip train_features.csv.zip

Archive:  train_features.csv.zip
replace train_features.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: ^C

In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)
df_train_features = pd.read_csv('/home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/kaggle_competition/train_features.csv')
df_train_features.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,scheme_name,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,Lake Nyasa,Mnyusi B,Iringa,11,5,Ludewa,Mundindi,109,True,GeoData Consultants Ltd,VWC,Roman,False,1999,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,Lake Victoria,Nyamara,Mara,20,2,Serengeti,Natta,280,NaN,GeoData Consultants Ltd,Other,NaN,True,2010,gravity,gravity,gravity,wug,user-group,never pay,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,Pangani,Majengo,Manyara,21,4,Simanjiro,Ngorika,250,True,GeoData Consultants Ltd,VWC,Nyumba ya mungu pipe scheme,True,2009,gravity,gravity,gravity,vwc,user-group,pay per bucket,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,Mahakamani,Mtwara,90,63,Nanyumbu,Nanyumbu,58,True,GeoData Consultants Ltd,VWC,NaN,True,1986,submersible,submersible,submersible,vwc,user-group,never pay,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,Lake Victoria,Kyanyamisa,Kagera,18,1,Karagwe,Nyakasimbi,0,True,GeoData Consultants Ltd,NaN,NaN,True,0,gravity,gravity,gravity,other,other,never pay,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe

In [8]:
df_train_features.columns

Index(['id', 'amount_tsh', 'date_recorded', 'funder', 'gps_height',
       'installer', 'longitude', 'latitude', 'wpt_name', 'num_private',
       'basin', 'subvillage', 'region', 'region_code', 'district_code', 'lga',
       'ward', 'population', 'public_meeting', 'recorded_by',
       'scheme_management', 'scheme_name', 'permit', 'construction_year',
       'extraction_type', 'extraction_type_group', 'extraction_type_class',
       'management', 'management_group', 'payment', 'payment_type',
       'water_quality', 'quality_group', 'quantity', 'quantity_group',
       'source', 'source_type', 'source_class', 'waterpoint_type',
       'waterpoint_type_group'],
      dtype='object')

In [3]:
df_train_labels = pd.read_csv('/home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/kaggle_competition/train_labels.csv')

In [4]:
df_train_labels.head()

      id    status_group
0  69572      functional
1   8776      functional
2  34310      functional
3  67743  non functional
4  19728      functional

In [11]:
df_train_labels.columns

Index(['id', 'status_group'], dtype='object')

In [12]:
df_train_features.shape

(59400, 40)

In [13]:
df_train_labels.shape

(59400, 2)

## majority Class Baseline

In [5]:
import numpy as np
majority_class = df_train_labels['status_group'].mode()[0]
#print(majority_class)

y_pred = np.full(shape=df_train_labels['status_group'].shape, fill_value=majority_class)

In [6]:
df_train_labels.status_group.shape, y_pred.shape

((59400,), (59400,))

In [7]:
all(y_pred==majority_class)

True

In [8]:
from sklearn.metrics import accuracy_score 
accuracy_score(df_train_labels['status_group'], y_pred)

0.543080808080808

In [9]:
submission_df = pd.DataFrame(y_pred, columns=['status_group_pred'])

In [10]:
submission_df.head()

  status_group_pred
0        functional
1        functional
2        functional
3        functional
4        functional

In [11]:
df_train_labels.head()

      id    status_group
0  69572      functional
1   8776      functional
2  34310      functional
3  67743  non functional
4  19728      functional

In [12]:
submission_baseline = pd.concat([df_train_labels, submission_df], axis=1)

In [13]:
submission_baseline.head()

      id    status_group status_group_pred
0  69572      functional        functional
1   8776      functional        functional
2  34310      functional        functional
3  67743  non functional        functional
4  19728      functional        functional

In [14]:
submission_baseline = submission_baseline.drop(columns='status_group')

In [15]:
submission_baseline.head()

      id status_group_pred
0  69572        functional
1   8776        functional
2  34310        functional
3  67743        functional
4  19728        functional

In [25]:
submission_baseline.to_csv('/home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/kaggle_competition/submission_baseline.csv')

### Class imbalance

In [16]:
df_train_labels['status_group'].value_counts()

functional                 32259
non functional             22824
functional needs repair     4317
Name: status_group, dtype: int64

In [17]:
df_train_labels['status_group'].value_counts(normalize=True)

functional                 0.543081
non functional             0.384242
functional needs repair    0.072677
Name: status_group, dtype: float64

In [18]:
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.metrics import accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression
from mlxtend.plotting import plot_decision_regions


#let's import the warning before running any sophisticated methods
import warnings
from sklearn.exceptions import DataConversionWarning
warnings.filterwarnings(action='ignore', category=DataConversionWarning)

In [19]:
import warnings
from sklearn.exceptions import DataConversionWarning
warnings.filterwarnings(action='ignore', category=DataConversionWarning)

#### How about printing our classification report

In [20]:
print(classification_report(df_train_labels['status_group'], y_pred) )

/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

                         precision    recall  f1-score   support

             functional       0.54      1.00      0.70     32259
functional needs repair       0.00      0.00      0.00      4317
         non functional       0.00      0.00      0.00     22824

              micro avg       0.54      0.54      0.54     59400
              macro avg       0.18      0.33      0.23     59400
           weighted avg       0.29      0.54      0.38     59400

Looking at the above report, it's a pretty bad prediction and recall.

In [ ]:
!kaggle competitions submit -c ds1-predictive-modeling-challenge -f /home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/kaggle_competition/submission_baseline.csv -m "testing submission command"

### Let's consider running a logistic regression only with numeric values

In [32]:
pd.set_option('display.max_columns', None)
df_train_features.head(5)

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,scheme_name,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,Lake Nyasa,Mnyusi B,Iringa,11,5,Ludewa,Mundindi,109,True,GeoData Consultants Ltd,VWC,Roman,False,1999,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,Lake Victoria,Nyamara,Mara,20,2,Serengeti,Natta,280,NaN,GeoData Consultants Ltd,Other,NaN,True,2010,gravity,gravity,gravity,wug,user-group,never pay,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,Pangani,Majengo,Manyara,21,4,Simanjiro,Ngorika,250,True,GeoData Consultants Ltd,VWC,Nyumba ya mungu pipe scheme,True,2009,gravity,gravity,gravity,vwc,user-group,pay per bucket,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,Mahakamani,Mtwara,90,63,Nanyumbu,Nanyumbu,58,True,GeoData Consultants Ltd,VWC,NaN,True,1986,submersible,submersible,submersible,vwc,user-group,never pay,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,Lake Victoria,Kyanyamisa,Kagera,18,1,Karagwe,Nyakasimbi,0,True,GeoData Consultants Ltd,NaN,NaN,True,0,gravity,gravity,gravity,other,other,never pay,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe

In [ ]:
df_train_features.shape

In [ ]:
df_train_features.head(-5)

## Let's check the Test file

In [21]:
#import pdandas as pd
df_test_features = pd.read_csv('/home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/kaggle_competition/test_features.csv')

In [22]:
df_test_features.shape

(14358, 40)

In [23]:
df_train_features.columns

Index(['id', 'amount_tsh', 'date_recorded', 'funder', 'gps_height',
       'installer', 'longitude', 'latitude', 'wpt_name', 'num_private',
       'basin', 'subvillage', 'region', 'region_code', 'district_code', 'lga',
       'ward', 'population', 'public_meeting', 'recorded_by',
       'scheme_management', 'scheme_name', 'permit', 'construction_year',
       'extraction_type', 'extraction_type_group', 'extraction_type_class',
       'management', 'management_group', 'payment', 'payment_type',
       'water_quality', 'quality_group', 'quantity', 'quantity_group',
       'source', 'source_type', 'source_class', 'waterpoint_type',
       'waterpoint_type_group'],
      dtype='object')

### merge Train and test sets
it's the same formula, just don't mention axis=1
The last row of our df_train_features dataset is 59394

In [293]:
#Let's merge train and test
full_df = pd.concat([df_train_features, df_test_features])

In [294]:
full_df.shape

(73758, 40)

In [ ]:
59400 + 14358

In [307]:
full_df.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,scheme_name,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group,construction_year_missing
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,Lake Nyasa,Mnyusi B,Iringa,11,5,Ludewa,Mundindi,109,True,GeoData Consultants Ltd,VWC,Roman,False,1999,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,0
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,Lake Victoria,Nyamara,Mara,20,2,Serengeti,Natta,280,NaN,GeoData Consultants Ltd,Other,NaN,True,2010,gravity,gravity,gravity,wug,user-group,never pay,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,0
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,Pangani,Majengo,Manyara,21,4,Simanjiro,Ngorika,250,True,GeoData Consultants Ltd,VWC,Nyumba ya mungu pipe scheme,True,2009,gravity,gravity,gravity,vwc,user-group,pay per bucket,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe,0
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,Mahakamani,Mtwara,90,63,Nanyumbu,Nanyumbu,58,True,GeoData Consultants Ltd,VWC,NaN,True,1986,submersible,submersible,submersible,vwc,user-group,never pay,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,0
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,Lake Victoria,Kyanyamisa,Kagera,18,1,Karagwe,Nyakasimbi,0,True,GeoData Consultants Ltd,NaN,NaN,True,1996,gravity,gravity,gravity,other,other,never pay,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,1

In [310]:
full_df['date_recorded_months'] = [(pd.to_datetime(date)-pd.to_datetime('2000-01-01')).days/30 for date in full_df['date_recorded']]

In [311]:
full_df.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,scheme_name,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group,construction_year_missing,date_recorded_months
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,Lake Nyasa,Mnyusi B,Iringa,11,5,Ludewa,Mundindi,109,True,GeoData Consultants Ltd,VWC,Roman,False,1999,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,0,136.333333
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,Lake Victoria,Nyamara,Mara,20,2,Serengeti,Natta,280,NaN,GeoData Consultants Ltd,Other,NaN,True,2010,gravity,gravity,gravity,wug,user-group,never pay,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,0,160.433333
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,Pangani,Majengo,Manyara,21,4,Simanjiro,Ngorika,250,True,GeoData Consultants Ltd,VWC,Nyumba ya mungu pipe scheme,True,2009,gravity,gravity,gravity,vwc,user-group,pay per bucket,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe,0,160.133333
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,Mahakamani,Mtwara,90,63,Nanyumbu,Nanyumbu,58,True,GeoData Consultants Ltd,VWC,NaN,True,1986,submersible,submersible,submersible,vwc,user-group,never pay,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,0,159.200000
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,Lake Victoria,Kyanyamisa,Kagera,18,1,Karagwe,Nyakasimbi,0,True,GeoData Consultants Ltd,NaN,NaN,True,1996,gravity,gravity,gravity,other,other,never pay,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,1,140.366667

In [312]:
#let's drop the columns with 28k nans 
full_df = full_df.drop(columns='scheme_name')

i'll take care of the misisng values in other columns now

In [313]:
#data['Native Country'] = data['Native Country'].fillna(data['Native Country'].mode()[0])
full_df['funder'] = full_df['funder'].fillna(full_df['funder'].mode()[0])

In [314]:
full_df['installer'] = full_df['installer'].fillna(full_df['installer'].mode()[0])

In [315]:
full_df['subvillage'] = full_df['subvillage'].fillna(full_df['subvillage'].mode()[0])

In [316]:
full_df['public_meeting'] = full_df['public_meeting'].fillna(full_df['public_meeting'].mode()[0])

In [317]:
full_df['scheme_management'] = full_df['scheme_management'].fillna(full_df['scheme_management'].mode()[0])

In [318]:
full_df['permit'] = full_df['permit'].fillna(full_df['permit'].mode()[0])

In [319]:
full_df = full_df.replace('none', np.NaN)

In [35]:
full_df.isna().sum()

id                          0
amount_tsh                  0
date_recorded               0
funder                      0
gps_height                  0
installer                   0
longitude                   0
latitude                    0
wpt_name                 4385
num_private                 0
basin                       0
subvillage                  0
region                      0
region_code                 0
district_code               0
lga                         0
ward                        0
population                  0
public_meeting              0
recorded_by                 0
scheme_management           0
permit                      0
construction_year           0
extraction_type             0
extraction_type_group       0
extraction_type_class       0
management                  0
management_group            0
payment                     0
payment_type                0
water_quality               0
quality_group               0
quantity                    0
quantity_group              0
source                      0
source_type                 0
source_class                0
waterpoint_type             0
waterpoint_type_group       0
dtype: int64

In [320]:
full_df['wpt_name'] = full_df['wpt_name'].fillna(full_df['wpt_name'].mode()[0])

In [321]:
full_df = full_df.replace('0', np.NaN)

In [322]:
full_df['installer'] = full_df['installer'].fillna(full_df['installer'].mode()[0])

### Dropping columns or feature engineering

In [325]:
full_df_selected_columns = full_df.drop(columns=['date_recorded','region','subvillage','installer','ward','lga','recorded_by','wpt_name', 'waterpoint_type_group','source', 'quality_group',
                                                'payment', 'management_group', 'extraction_type',
                                                'extraction_type_group', 'num_private' 
                                                 , 'funder'])

In [277]:
full_df.gps_height.isna().sum()

0

In [326]:
full_df.head(100)

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group,construction_year_missing,date_recorded_months
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322e+00,Shuleni,0,Lake Nyasa,Mnyusi B,Iringa,11,5,Ludewa,Mundindi,109,True,GeoData Consultants Ltd,VWC,False,1999,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,0,136.333333
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466e+00,Zahanati,0,Lake Victoria,Nyamara,Mara,20,2,Serengeti,Natta,280,True,GeoData Consultants Ltd,Other,True,2010,gravity,gravity,gravity,wug,user-group,never pay,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,0,160.433333
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329e+00,Kwa Mahundi,0,Pangani,Majengo,Manyara,21,4,Simanjiro,Ngorika,250,True,GeoData Consultants Ltd,VWC,True,2009,gravity,gravity,gravity,vwc,user-group,pay per bucket,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe,0,160.133333
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-1.115530e+01,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,Mahakamani,Mtwara,90,63,Nanyumbu,Nanyumbu,58,True,GeoData Consultants Ltd,VWC,True,1986,submersible,submersible,submersible,vwc,user-group,never pay,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,0,159.200000
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359e+00,Shuleni,0,Lake Victoria,Kyanyamisa,Kagera,18,1,Karagwe,Nyakasimbi,0,True,GeoData Consultants Ltd,VWC,True,1996,gravity,gravity,gravity,other,other,never pay,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,1,140.366667
5,9944,20.0,2011-03-13,Mkinga Distric Coun,0,DWE,39.172796,-4.765587e+00,Tajiri,0,Pangani,Moa/Mwereme,Tanga,4,8,Mkinga,Moa,1,True,GeoData Consultants Ltd,VWC,True,2009,submersible,submersible,submersible,vwc,user-group,pay per bucket,per bucket,salty,salty,enough,enough,other,other,unknown,communal standpipe multiple,communal standpipe,0,136.300000
6,19816,0.0,2012-10-01,Dwsp,0,DWSP,33.362410,-3.766365e+00,Kwa Ngomho,0,Internal,Ishinabulandi,Shinyanga,17,3,Shinyanga Rural,Samuye,0,True,GeoData Consultants Ltd,VWC,True,1996,swn 80,swn 80,handpump,vwc,user-group,never pay,never pay,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump,1,155.233333
7,54551,0.0,2012-10-09,Rwssp,0,DWE,32.620617,-4.226198e+00,Tushirikiane,0,Lake Tanganyika,Nyawishi Center,Shinyanga,17,3,Kahama,Chambo,0,True,GeoData Consultants Ltd,VWC,True,1996,nira/tanira,nira/tanira,handpump,wug,user-group,unknown,unknown,milky,milky,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump,1,155.500000
8,53934,0.0,2012-11-03,Wateraid,0,Water Aid,32.711100,-5.146712e+00,Kwa Ramadhan Musa,0,Lake Tanganyika,Imalauduki,Tabora,14,6,Tabora Urban,Itetemia,0,True,GeoData Consultants Ltd,VWC,True,1996,india mark ii,india mark ii,handpump,vwc,user-group,never pay,never pay,salty,salty,seasonal,seasonal,machine dbh,borehole,groundwater,hand pump,hand pump,1,156.333333
9,46144,0.0,2011-08-03,Isingiro Ho,0,Artisan,30.626991,-1.257051e+00,Kwapeto,0,Lake Victoria,Mkonomre,Kagera,18,1,Karagwe,Kaisho,0,True,GeoData Consultants Ltd,VWC,True,1996,nira/tanira,nira/tanira,handpump,vwc,user-group,never pay,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump,1,141.066667
10,49056,0.0,2011-02-20,Private,62,Private,39.209518,-7.034139e+00,Mzee Hokororo,0,Wami / Ruvu,Mizugo,Pwani,60,43,Mkuranga,Tambani,345,True,GeoData Consultants Ltd,Private operator,False,2011,submersible,submersible,submersible,private operator,commercial,never pay,never pay,salty,salty,enough,enough,machine dbh,borehole,groundwater,other,other,0,135.600000
11,50409,200.0,2013-02-18,Danida,1062,DANIDA,35.770258,-1.057417e+01,Kwa Alid Nchimbi,0,Lake Nyasa,Ngondombwito,Ruvuma,10,5,Namtumbo,Msindo,250,True,GeoData Consultants Ltd,WUG,False,1987,swn 80,swn 80,handpump,wug,user-group,pay when scheme fails,on failure,soft,good,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump,0,159.900000
12,36957,0.0,2012-10-14,World Vision,0,World vision,33.798106,-3.290194e+00,Pamba,0,Internal,Nkilifa,Shinyanga,17,2,Maswa,Busilili,0,True,GeoData Consultants Ltd,WUG,False,1996,nira/tanira,nira/tanira,handpump,wug,user-group,other,other,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump,1,155.666667
13,50495,0.0,2013-03-15,Lawatefuka Water Supply,1368,Lawatefuka water sup,37.092574,-3.181783e+00,Kwa John Izack Mmari,0,Pangani,Omarini,Kilimanjaro,3,7,Siha,Siha Kaskazini,1,True,GeoData Consultants Ltd,Water Board,True,2009,gravity,gravity,gravity,water board,user-group,pay monthly,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,0,160.733333
14,53752,0.0,2012-10-20,Biore,0,WEDECO,34.364073,-3.629333e+00,Mwabasabi,0,Internal,Mwabasabi,Shinyanga,17,6,Meatu,Nkoma,0,True,GeoData Consultants Ltd,WUG,True,1996,nira/tanira,nira/tanira,handpump,wug,user-group,never pay,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump,1,155.866667
15,61848,0.0,2011-08-04,Rudep,1645,DWE,31.444121,-8.274962e+00,Kwa Juvenal Ching'Ombe,0,Lake Tanganyika,Tunzi,Rukwa,15,2,Sumbawanga Rural,Mkowe,200,True,GeoData Consultants Ltd,VWC,False,1991,swn 80,swn 80,handpump,vwc,user-group,never pay,never pay,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump,0,141.100000
16,48451,500.0,2011-07-04,Unicef,1703,DWE,34.642439,-9.106185e+00,Kwa John Mtenzi,0,Rufiji,Kidudumo,Iringa,11,4,Njombe,Mdandu,35,True,GeoData Consultants Ltd,WUA,True,1978,gravity,gravity,gravity,wua,user-group,pay monthly,monthly,soft,good,dry,dry,river,river/lake,surface,communal standpipe,communal standpipe,0,140.066667
17,58155,0.0,2011-09-04,Unicef,1656,DWE,34.569266,-9.085515e+00,Kwa Rose Chaula,0,Rufiji,Yeriko,Iringa,11,4,Njombe,Usuka,50,True,GeoData Consultants Ltd,WUA,True,1978,gravity,gravity,gravity,wua,user-group,pay when scheme fails,on failure,soft,good,dry,dry,river,river/lake,surface,communal standpipe,communal standpipe,0,142.133333
18,34169,0.0,2011-07-22,Hesawa,1162,DWE,32.920154,-1.947868e+00,Ngomee,0,Lake Victoria,Center,Mwanza,19,1,Ukerewe,Ilangala,1000,True,GeoData Consultants Ltd,VWC,True,1999,other,other,other,vwc,user-group,never pay,never pay,milky,milky,insufficient,insufficient,spring,spring,groundwater,other,other,0,140.666667
19,18274,500.0,2011-02-22,Danida,1763,Danid,34.508967,-9.894412e+00,Shuleni,0,Lake Nyasa,Manyanya,Iringa,11,5,Ludewa,Mawengi,1,True,GeoData Consultants Ltd,VWC,True,1992,gravity,gravity,gravity,vwc,user-group,pay annually,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,0,135.666667
20,48375,200.0,2011-02-27,Twe,2216,TWE,34.473430,-9.594990e+00,Shuleni,0,Lake Nyasa,Majengo,Iringa,11,4,Njombe,Matola,4,True,GeoData Consultants Ltd,VWC,False,2008,gravity,gravity,gravity,vwc,user-group,pay monthly,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,0,135.833333
21,6091,0.0,2013-02-10,Dwsp,0,DWE,0.000000,-2.000000e-08,Muungano,0,Lake Victoria,Ibabachegu,Shinyanga,17,1,Bariadi,Ikungulyabashashi,0,True,GeoData Consultants Ltd,WUG,False,1996,swn 80,swn 80,handpump,wug,user-group,unknown,unknown,unknown,unknown,unknown,unknown,shallow well,shallow well,groundwater,hand pump,hand pump,1,159.633333
22,58500,0.0,2011-10-04,Unicef,1510,DWE,34.586901,-8.980014e+00,Shuleni,0,Rufiji,Mkanivega,Iringa,11,4,Njombe,Usuka,350,True,GeoData Consultants Ltd,WUA,True,1978,gravity,gravity,gravity,wua,user-group,never pay,never pay,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe,0,143.133333
23,37862,500.0,2013-11-03,Isf,672,ISF,37.940029,-4.125595e+00,Kinonga,0,Pangani,Mkonga Juu,Kilimanjaro,3,3,Same,Kisiwani,210,True,GeoData Consultants Ltd,Water authority,True,2011,gravity,gravity,gravity,vwc,user-group,pay monthly,monthly,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe,0,168.500000
24,51058,0.0,2013-01-21,African Development Bank,1645,DWE,29.747066,-4.495568e+00,Kamsasa,0,Lake Tanganyika,Msasa,Kigoma,16,3,Kigoma Rural,Mkigo,156,False,GeoData Consultants Ltd,VWC,True,2009,gravity,gravity,gravity,vwc,user-group,unknown,unknown,soft,good,enough,enough,spring,spring,groundwater,improved spring,improved spring,0,158.966667
25,22308,0.0,2013-02-25,Government Of Tanzania,1273,DWE,37.422751,-3.317536e+00,Kwa Tukai,0,Pangani,Kitereni,Kilimanjaro,3,4,Moshi Rural,Kimochi,140,True,GeoData Consultants Ltd,VWC,True,1974,gravity,gravity,gravity,vwc,user-group,unknown,unknown,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,0,160.133333
26,55012,500.0,2013-01-16,Sobodo,200,Kilolo Star,39.370777,-9.942532e+00,Ruhoma Primary School,0,Ruvuma / Southern Coast,Shuleni,Lindi,80,23,Lindi Rural,Rutamba,260,False,GeoData Consultants Ltd,VWC,False,2011,india mark ii,india mark ii,handpump,vwc,user-group,pay monthly,monthly,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump,0,158.800000
27,20145,0.0,2011-07-11,Hesawa,0,DWE,31.104257,-1.735361e+00,Kwawilliam,0,Lake Victoria,Chakahaya,Kagera,18,1,Karagwe,Nyaishozi,0,True,GeoData Consultants Ltd,VWC,True,1996,nira/tanira,nira/tanira,handpump,vwc,user-group,never pay,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump,1,140.300000
28,19685,0.0,2013-03-05,Government Of Tanzania,1443,District council,37.611126,-3.263526e+00,Kwa Kibakaya,0,Pangani,Kiyao,Kilimanjaro,3,1,Rombo,Mengwe Manda,1,True,GeoData Consultants Ltd,Company,True,2000,gravity,gravity,gravity,company,commercial,pay monthly,monthly,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe,0,160.400000
29,69124,0.0,2013-03-16,Lawatefuka Water Supply,1256,Lawatefuka water sup,37.061688,-3.191989e+00,Kwa Willium Kinda,0,Pangani,Merali,Kilimanjaro,3,7,Siha,Siha Kati,1,True,GeoData Consultants Ltd,Water Board,True,2002,gravity,gravity,gravity,water board,user-group,pay monthly,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,0,160.766667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,21990,200.0,2011-03-05,Government Of Tanzania,303,RWE,35.818981,-8.934950e+00,Kwampalanji,0,Rufiji,Mtakuja,Morogoro,5,3,Kilombero,Utengule,280,True,GeoData Consultants Ltd,VWC,True,1995,swn 80,swn 80,handpump,vwc,user-group,pay monthly,monthly,unknown,unknown,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump,0,136.033333
71,17386,0.0,2011-03-31,Government Of Tanzania,0,DWE,34.462228,-8.575780e+00,Kwa Manyusi Mlilo,0,Rufiji,Lembuka,Mbeya,12,7,Mbarali,Mawindi,0,True,GeoData Consultants Ltd,VWC,False,1996,gravity,gravity,gravity,vwc,user-group,never pay,never pay,soft,good,insufficient,insufficient,river,river/lake,surface,communal standpipe,communal standpipe,1,136.900000
72,41609,0.0,2011-04-04,Government Of Tanzania,0,DWE,34.247180,-8.607513e+00,Kwa Mzee Mwalongo,0,Rufiji,Mapinduzi,Mbeya,12,7,Mbarali,Ubaruku,0,True,GeoData Consultants Ltd,VWC,True,1996,gravity,gravity,gravity,vwc,user-group,never pay,never pay,soft,good,seasonal,seasonal,river,river/lake,surface,communal standpipe,communal standpipe,1,137.033333
73,35715,0.0,2013-02-27,Hesawa,1565,HESAWA,34.657034,-1.888020e+00,Machumbe,0,Lake Victoria,Mtakuja,Mara,20,2,Serengeti,Manchira,200,True,GeoData Consultants Ltd,Other,True,1991,nira/tanira,nira/tanira,handpump,wug,user-group,other,other,soft,good,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump,0,160.200000
74,53970,500.0,2013-01-16,Dwe,1153,DWE,30.419958,-4.279968e+00,Sekondari,0,Lake Tanganyika,Kalimungoma,Kigoma,16,2,Kasulu,Kitagata,1,True,GeoData Consultants Ltd,Water authority,False,2009,nira/tanira,nira/tanira,handpump,vwc,user-group,pay when scheme fails,on failure,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump,0,158.800000
75,62971,0.0,2011-08-07,Government Of Tanzania,0,DWE,31.796873,-1.351486e+00,Kwa Jackson,0,Lake Victoria,Umkituri,Kagera,18,6,Bukoba Urban,Kibeta,0,True,GeoData Consultants Ltd,VWC,False,1996,submersible,submersible,submersible,vwc,user-group,never pay,never pay,soft,good,insufficient,insufficient,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,1,141.200000
76,63542,500.0,2011-03-23,Rc Church,2049,ACRA,34.680471,-9.326477e+00,Kwa Mkapa,0,Rufiji,Usita,Iringa,11,4,Njombe,Imalinyi,75,True,GeoData Consultants Ltd,WUA,True,2008,gravity,gravity,gravity,wua,user-group,pay monthly,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,0,136.633333
77,15622,0.0,2013-03-18,Government Of Tanzania,905,RWE,36.931659,-3.557034e+00,Miembeni Primary School,0,Pangani,Komoro,Arusha,2,7,Meru,Mbuguni,140,True,GeoData Consultants Ltd,VWC,True,1974,gravity,gravity,gravity,vwc,user-group,unknown,unknown,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe,0,160.833333
78,12903,0.0,2011-03-30,Government Of Tanzania,406,DWE,38.580824,-4.834836e+00,Tawakali,0,Pangani,Kulasi Majengo,Tanga,4,2,Korogwe,Mashewa,900,True,GeoData Consultants Ltd,VWC,False,1992,gravity,gravity,gravity,vwc,user-group,never pay,never pay,soft,good,dry,dry,river,river/lake,surface,communal standpipe,communal standpipe,0,136.866667
79,52561,0.0,2012-10-23,World Vision,0,World vision,32.255005,-3.361901e+00,Butimba,0,Lake Tanganyika,Butimba,Shinyanga,17,5,Bukombe,Ushirika,0,True,GeoData Consultants Ltd,VWC,True,1996,nira/tanira,nira/tanira,handpump,vwc,user-group,unknown,unknown,soft,good,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump,1,155.966667
80,19415,0.0,2011-03-02,Roman,2328,Commu,34.284476,-9.271565e+00,Shuleni,0,Lake Nyasa,Ikovo,Iringa,11,3,Makete,Mang'oto,0,True,GeoData Consultants Ltd,VWC,False,2002,gravity,gravity,gravity,vwc,user-group,never pay,never pay,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,0,135.933333
81,65531,0.0,2011-03-04,Roman,427,Roman,37.722953,-7.024263e+00,Kwa Mzee Zewe,0,Wami / Ruvu,Dongo,Morogoro,5,2,Morogoro Rural,Tawa,100,True,GeoData Consultants Ltd,VWC,True,2004,gravity,gravity,gravity,vwc,user-group,never pay,never pay,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe,0,136.000000
82,3675,0.0,2013-03-14,Swisland/ Mount Meru Flowers,1331,Community,36.757932,-3.374791e+00,Lonange Secschool,0,Pangani,Moivaro,Arusha,2,7,Meru,Nkoanrua,360,True,GeoData Consultants Ltd,WUA,True,2011,gravity,gravity,gravity,wua,user-group,unknown,unknown,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,0,160.700000
83,34383,0.0,2012-10-22,Rwssp,0,DWE,33.538909,-3.361612e+00,Lembo,0,Internal,Bushoma,Shinyanga,17,8,Kishapu,Mondo,0,True,GeoData Consultants Ltd,WUG,False,1996,nira/tanira,nira/tanira,handpump,wug,user-group,pay when scheme fails,on failure,soft,good,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump,1,155.933333
84,30423,0.0,2012-10-18,Ifad,1185,IFAD,34.190575,-1.609691e+00,Shuleni,0,Lake Victoria,Shule,Mara,20,3,Musoma Rural,Buswahili,544,True,GeoData Consultants Ltd,Parastatal,False,2002,gravity,gravity,gravity,parastatal,parastatal,unknown,unknown,soft,good,enough,enough,rainwater harvesting,rainwater harvesting,surface,hand pump,hand pump,0,155.800000
85,68717,0.0,2011-08-08,Swedish,0,Sengerema Water Department,32.185517,-2.378772e+00,Kwa Swakala,0,Lake Victoria,Bulyahilu Center B,Mwanza,19,5,Sengerema,Bupandwamhela,0,True,GeoData Consultants Ltd,VWC,True,1996,nira/tanira,nira/tanira,handpump,vwc,user-group,never pay,never pay,soft,good,seasonal,seasonal,shallow well,shallow well,groundwater,hand pump,hand pump,1,141.233333
86,3688,500.0,2011-02-20,Idc,1701,DWE,35.734474,-7.912317e+00,Shuleni,0,Rufiji,Mlanda B,Iringa,11,1,Iringa Rural,Magulilwa,441,True,GeoData Consultants Ltd,VWC,True,2000,swn 80,swn 80,handpump,vwc,user-group,pay monthly,monthly,soft,good,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump,0,135.600000
87,30537,0.0,2011-09-05,He,0,HE,31.558903,-2.026469e+00,Kwa Ignas,0,Lake Victoria,Kasharunga,Kagera,18,3,Muleba,Kasharunga,0,True,GeoData Consultants Ltd,VWC,False,1996,gravity,gravity,gravity,vwc,user-group,never pay,never pay,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe,1,142.166667
88,27312,50.0,2011-03-12,Private Individual,159,WU,38.353567,-6.638696e+00,Kessy,0,Wami / Ruvu,Magwila,Pwani,6,1,Bagamoyo,Chalinze,20,False,GeoData Consultants Ltd,WUA,True,2008,ksb,submersible,submersible,private operator,commercial,pay per bucket,per bucket,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe,0,136.266667
89,22143,0.0,2011-04-11,Water,0,Commu,35.878172,-5.891868e+00,Ofisini,0,Wami / Ruvu,Juhudi,Dodoma,1,5,Dodoma Urban,Chihanga,0,True,GeoData Consultants Ltd,VWC,False,1996,mono,mono,motorpump,vwc,user-group,pay per bucket,per bucket,soft,good,insufficient,insufficient,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,1,137.266667
90,43237,200.0,2013-01-17,Isf/tacare,1002,ISF and TACARE,29.670989,-4.726850e+00,Muungano,0,Lake Tanganyika,Kilundo,Kigoma,16,3,Kigoma Rural,Mwamgongo,120,True,GeoData Consultants Ltd,WUG,True,2006,gravity,gravity,gravity,vwc,user-group,pay monthly,monthly,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe,0,158.833333
91,62591,0.0,2013-01-20,Jica,212,Kokeni,38.962945,-1.047657e+01,Maringini,0,Ruvuma / Southern Coast,Mwena,Lindi,80,53,Ruangwa,Luchelegwa,280,True,GeoData Consultants Ltd,VWC,True,2006,india mark iii,india mark iii,handpump,vwc,user-group,never pay,never pay,salty,salty,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump,0,158.933333
92,39920,200.0,2011-03-23,Danida,18,DA,38.890402,-6.557903e+00,Gedebu,0,Wami / Ruvu,Shule,Pwani,6,1,Bagamoyo,Kiromo,40,True,GeoData Consultants Ltd,Company,True,1987,ksb,submersible,submersible,vwc,user-group,pay monthly,monthly,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe,0,136.633333
93,70892,0.0,2013-02-18,Adra,1560,Adra,35.512174,-4.448040e+00,Gadiehindo,0,Internal,Mara B,Manyara,21,2,Hanang,Measkron,221,True,GeoData Consultants Ltd,VWC,True,2008,gravity,gravity,gravity,vwc,user-group,never pay,never pay,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe,0,159.900000
94,48593,0.0,2011-07-11,Hesawa,0,DWE,31.453111,-1.194390e+00,Kagashani,0,Lake Victoria,Mushasha,Kagera,18,7,Misenyi,Kyaka,0,True,GeoData Consultants Ltd,VWC,True,1996,nira/tanira,nira/tanira,handpump,vwc,user-group,never pay,never pay,milky,milky,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump,1,140.300000

In [327]:
full_df['construction_year_missing'] = (full_df['construction_year'] ==0)*1

In [329]:
full_df_selected_columns.head()

,id,amount_tsh,gps_height,longitude,latitude,basin,region_code,district_code,population,public_meeting,scheme_management,permit,construction_year,extraction_type_class,management,payment_type,water_quality,quantity,quantity_group,source_type,source_class,waterpoint_type,construction_year_missing,date_recorded_months
0,69572,6000.0,1390,34.938093,-9.856322,Lake Nyasa,11,5,109,True,VWC,False,1999,gravity,vwc,annually,soft,enough,enough,spring,groundwater,communal standpipe,0,136.333333
1,8776,0.0,1399,34.698766,-2.147466,Lake Victoria,20,2,280,True,Other,True,2010,gravity,wug,never pay,soft,insufficient,insufficient,rainwater harvesting,surface,communal standpipe,0,160.433333
2,34310,25.0,686,37.460664,-3.821329,Pangani,21,4,250,True,VWC,True,2009,gravity,vwc,per bucket,soft,enough,enough,dam,surface,communal standpipe multiple,0,160.133333
3,67743,0.0,263,38.486161,-11.155298,Ruvuma / Southern Coast,90,63,58,True,VWC,True,1986,submersible,vwc,never pay,soft,dry,dry,borehole,groundwater,communal standpipe multiple,0,159.200000
4,19728,0.0,0,31.130847,-1.825359,Lake Victoria,18,1,0,True,VWC,True,1996,gravity,other,never pay,soft,seasonal,seasonal,rainwater harvesting,surface,communal standpipe,1,140.366667

In [328]:
#before filling the null, let's keep track of them
#https://towardsdatascience.com/water-pumps-maintenance-prediction-data-science-illustrated-20c7100017c5
import datetime
from dateutil import parser
import numpy as np

#to fill missing dates, we can use: mean, median or the oldest
mean_year = full_df[full_df['construction_year']>0]['construction_year'].mean()
full_df.loc[full_df['construction_year']==0, 'construction_year'] = int(mean_year)

In [289]:
full_df.construction_year.mean()

1.0

### feauture Engineering

In [181]:
#full_df_selected_columns['average_amount'] = full_df_selected_columns['amount_tsh']/ full_df_selected_columns['population']

In [330]:
import pandas as pd
df_main = pd.get_dummies(full_df_selected_columns)
#pd.set_option('display.max_columns', None)

In [331]:
df_main.head()

,id,amount_tsh,gps_height,longitude,latitude,region_code,district_code,population,public_meeting,permit,construction_year,construction_year_missing,date_recorded_months,basin_Internal,basin_Lake Nyasa,basin_Lake Rukwa,basin_Lake Tanganyika,basin_Lake Victoria,basin_Pangani,basin_Rufiji,basin_Ruvuma / Southern Coast,basin_Wami / Ruvu,scheme_management_Company,scheme_management_None,scheme_management_Other,scheme_management_Parastatal,scheme_management_Private operator,scheme_management_SWC,scheme_management_Trust,scheme_management_VWC,scheme_management_WUA,scheme_management_WUG,scheme_management_Water Board,scheme_management_Water authority,extraction_type_class_gravity,extraction_type_class_handpump,extraction_type_class_motorpump,extraction_type_class_other,extraction_type_class_rope pump,extraction_type_class_submersible,extraction_type_class_wind-powered,management_company,management_other,management_other - school,management_parastatal,management_private operator,management_trust,management_unknown,management_vwc,management_water authority,management_water board,management_wua,management_wug,payment_type_annually,payment_type_monthly,payment_type_never pay,payment_type_on failure,payment_type_other,payment_type_per bucket,payment_type_unknown,water_quality_coloured,water_quality_fluoride,water_quality_fluoride abandoned,water_quality_milky,water_quality_salty,water_quality_salty abandoned,water_quality_soft,water_quality_unknown,quantity_dry,quantity_enough,quantity_insufficient,quantity_seasonal,quantity_unknown,quantity_group_dry,quantity_group_enough,quantity_group_insufficient,quantity_group_seasonal,quantity_group_unknown,source_type_borehole,source_type_dam,source_type_other,source_type_rainwater harvesting,source_type_river/lake,source_type_shallow well,source_type_spring,source_class_groundwater,source_class_surface,source_class_unknown,waterpoint_type_cattle trough,waterpoint_type_communal standpipe,waterpoint_type_communal standpipe multiple,waterpoint_type_dam,waterpoint_type_hand pump,waterpoint_type_improved spring,waterpoint_type_other
0,69572,6000.0,1390,34.938093,-9.856322,11,5,109,True,False,1999,0,136.333333,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0
1,8776,0.0,1399,34.698766,-2.147466,20,2,280,True,True,2010,0,160.433333,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0
2,34310,25.0,686,37.460664,-3.821329,21,4,250,True,True,2009,0,160.133333,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
3,67743,0.0,263,38.486161,-11.155298,90,63,58,True,True,1986,0,159.200000,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0
4,19728,0.0,0,31.130847,-1.825359,18,1,0,True,True,1996,1,140.366667,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0

In [258]:
df_main.shape

(73758, 460)

### Now since we took care of our missing values, let's get our X matrix and y first

In [332]:
#split the data back
X_cleaned = df_main[:-14358]
X_test_main_cleaned = df_main[-14358:]
y = df_train_labels['status_group']

In [333]:
X_cleaned.shape, X_test_main_cleaned.shape, y.shape

((59400, 95), (14358, 95), (59400,))

In [334]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_cleaned, y, test_size=0.25, random_state=42, shuffle=True)

In [261]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((44550, 460), (14850, 460), (44550,), (14850,))

In [ ]:
!pip install category_encoders

In [ ]:
# #let's use OneHot Encoding before we try standard scaler
# from sklearn.pipeline import make_pipeline
# import category_encoders as ce
# pipeline = make_pipeline(
#     ce.OneHotEncoder(use_cat_names=True), 
#                         LogisticRegression(solver='newton-cg', multi_class='multinomial'))

# pipeline.fit(X_train, y_train)
# y_pred = pipeline.predict(X_test_main_cleaned)

In [ ]:
accuracy_score(y_test, y_pred)

In [55]:
y_train.head()

24947    non functional
22630        functional
13789        functional
15697        functional
22613    non functional
Name: status_group, dtype: object

Let's try another baseline with only numeric features

In [91]:
# from sklearn.preprocessing import LabelEncoder
# def dummyEncode(df):
#         columnsToEncode = list(df.select_dtypes(include=['category','object']))
#         le = LabelEncoder()
#         for feature in columnsToEncode:
#             try:
#                 df[feature] = le.fit_transform(df[feature])
#             except:
#                 print('Error encoding '+feature)
#         return df

In [92]:
# cat_coded_df = dummyEncode(X_cleaned)

/home/mishraka/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [61]:
# cat_coded_df.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,69572,6000.0,47,1369,1390,1518,34.938093,-9.856322,37399,0,1,11807,3,11,5,51,1426,109,True,0,7,False,1999,3,1,0,7,4,2,0,6,2,1,1,8,6,0,1,1
1,8776,0.0,309,469,1399,545,34.698766,-2.147466,37195,0,4,15838,9,20,2,103,1576,280,True,0,2,True,2010,3,1,0,11,4,0,2,6,2,2,2,5,3,1,1,1
2,34310,25.0,300,825,686,2048,37.460664,-3.821329,14572,0,5,9074,8,21,4,108,1624,250,True,0,7,True,2009,3,1,0,7,4,4,5,6,2,1,1,0,1,1,2,1
3,67743,0.0,272,1741,263,1852,38.486161,-11.155298,37285,0,7,8982,12,90,63,87,1571,58,True,0,7,True,1986,14,10,5,7,4,0,2,6,2,0,0,3,0,0,2,1
4,19728,0.0,104,20,0,119,31.130847,-1.825359,35529,0,4,7698,4,18,1,26,1687,0,True,0,7,True,0,3,1,0,1,1,0,2,6,2,3,3,5,3,1,1,1

In [93]:
# X_test_submission_cleaned = dummyEncode(X_test_main_cleaned)

/home/mishraka/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [65]:
# X_test_submission_cleaned.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,50785,0.0,255,174,1996,214,35.290799,-4.059696,633,0,0,3807,8,21,3,62,16,321,True,0,2,True,2012,9,6,3,3,2,0,2,6,2,3,3,5,3,1,6,5
1,51630,0.0,255,247,1569,219,36.656709,-3.309214,1727,0,5,2634,0,2,2,0,642,300,True,0,6,True,2000,3,1,0,7,4,0,2,6,2,2,2,8,6,0,1,1
2,17168,0.0,252,247,1567,219,34.767863,-5.004344,9483,0,0,5271,18,13,2,108,1659,500,True,0,6,True,2010,9,6,3,7,4,0,2,6,2,2,2,5,3,1,6,5
3,45559,0.0,242,220,267,259,38.058046,-9.418672,5467,0,7,2710,7,80,43,48,1178,250,True,0,6,True,1987,9,6,3,7,4,6,6,6,2,0,0,7,5,0,6,5
4,49871,500.0,306,72,1260,75,35.006123,-10.950412,5573,0,7,3442,16,10,3,60,1061,60,True,0,9,True,2000,3,1,0,9,4,3,1,6,2,1,1,8,6,0,1,1

In [94]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(cat_coded_df, y, test_size=0.25, random_state=42, shuffle=True)

In [189]:
X_cleaned.shape, y.shape

((59400, 106), (59400,))

In [76]:
import warnings
from sklearn.exceptions import DataConversionWarning
warnings.filterwarnings(action='ignore', category=DataConversionWarning)

In [211]:
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.metrics import accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression
from mlxtend.plotting import plot_decision_regions
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score
from sklearn.feature_selection import f_classif, SelectKBest

pipeline = make_pipeline(StandardScaler(), SelectKBest(f_classif),
                        LogisticRegression(solver='newton-cg', multi_class='auto'))

pipeline.fit(X_cleaned, y)

Pipeline(memory=None,
     steps=[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('selectkbest', SelectKBest(k=10, score_func=<function f_classif at 0x7f29b3538c80>)), ('logisticregression', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='auto',
          n_jobs=None, penalty='l2', random_state=None, solver='newton-cg',
          tol=0.0001, verbose=0, warm_start=False))])

In [212]:
scores = cross_val_score(pipeline, X_cleaned, y, scoring='accuracy', cv=10)

/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [19] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw

In [213]:
scores

array([0.7000505 , 0.69129776, 0.69634742, 0.68910958, 0.70286195,
       0.69612795, 0.7016835 , 0.69388786, 0.70213841, 0.7034355 ])

In [214]:
scores.mean()

0.697694041953127

In [110]:
y_pred = pipeline.predict(X_test_main_cleaned)

In [111]:
X_test_main_cleaned.shape, y_pred.shape

((14358, 474), (14358,))

In [131]:
submission_third_file = pd.DataFrame(X_test_main_cleaned.id.values, columns=['id'])

In [132]:
submission_third_file.head()

      id
0  50785
1  51630
2  17168
3  45559
4  49871

In [133]:
submission_third_file.shape

(14358, 1)

In [134]:
y = pd.DataFrame(y_pred, columns=['status_group'])

In [115]:
y.shape

(14358, 1)

In [135]:
submission_third = pd.concat([submission_third_file, y], axis=1)

In [136]:
submission_third.shape

(14358, 2)

In [137]:
submission_third.to_csv('/home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/kaggle_competition/submission_third.csv', index=False)

In [138]:
!kaggle competitions submit -c ds1-predictive-modeling-challenge -f /home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/kaggle_competition/submission_third.csv -m "third submission command"

100%|█████████████████████████████████████████| 249k/249k [00:01<00:00, 196kB/s]
Successfully submitted to DS1 Predictive Modeling Challenge

In [ ]:
df = pd.read_csv("/home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/kaggle_competition/submission_second.csv")

In [ ]:
df.head()

In [160]:
pipeline = make_pipeline(StandardScaler(), 
                         SelectKBest(f_classif), 
                         LogisticRegression(solver='newton-cg', multi_class='multinomial'))

param_grid = {
    'selectkbest__k': [1,2,3,4], 
    'logisticregression__C': [.0001, .001, .01, .1, 1.0, 10.0, 100.00, 1000.0, 10000.0],
    'logisticregression__class_weight':[None, 'balanced']
}

In [163]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import recall_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score
from sklearn.feature_selection import f_classif, SelectKBest

gs = GridSearchCV(pipeline,param_grid=param_grid, cv=5, 
                  scoring='accuracy', 
                  verbose=1)

In [164]:
gs.fit(X_train, y_train)

Fitting 5 folds for each of 72 candidates, totalling 360 fits

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  11  12  13  14  15  17  18  19  23  26 166 167 170 175 176
 177 178 181 184 186 188 189 190 192 195 205 206 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  26 166 168 170 174 175 178 180 183
 184 188 190 192 195 268 374 408] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  21  26 166 170 173 175 178 179 182
 184 185 188 190 192 193 194 195 196 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  22  26 166 170 175 178 184 188 190
 192 195 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  26 166 169 170 175 178 184 187 188
 190 191 192 195 271 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  11  12  13  14  15  17  18  19  23  26 166 167 170 175 176
 177 178 181 184 186 188 189 190 192 195 205 206 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  26 166 168 170 174 175 178 180 183
 184 188 190 192 195 268 374 408] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  21  26 166 170 173 175 178 179 182
 184 185 188 190 192 193 194 195 196 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  22  26 166 170 175 178 184 188 190
 192 195 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  26 166 169 170 175 178 184 187 188
 190 191 192 195 271 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  11  12  13  14  15  17  18  19  23  26 166 167 170 175 176
 177 178 181 184 186 188 189 190 192 195 205 206 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  26 166 168 170 174 175 178 180 183
 184 188 190 192 195 268 374 408] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  21  26 166 170 173 175 178 179 182
 184 185 188 190 192 193 194 195 196 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  22  26 166 170 175 178 184 188 190
 192 195 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  26 166 169 170 175 178 184 187 188
 190 191 192 195 271 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  11  12  13  14  15  17  18  19  23  26 166 167 170 175 176
 177 178 181 184 186 188 189 190 192 195 205 206 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  26 166 168 170 174 175 178 180 183
 184 188 190 192 195 268 374 408] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw

/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  21  26 166 170 173 175 178 179 182
 184 185 188 190 192 193 194 195 196 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  22  26 166 170 175 178 184 188 190
 192 195 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  26 166 169 170 175 178 184 187 188
 190 191 192 195 271 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  11  12  13  14  15  17  18  19  23  26 166 167 170 175 176
 177 178 181 184 186 188 189 190 192 195 205 206 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  26 166 168 170 174 175 178 180 183
 184 188 190 192 195 268 374 408] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  21  26 166 170 173 175 178 179 182
 184 185 188 190 192 193 194 195 196 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  22  26 166 170 175 178 184 188 190
 192 195 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  26 166 169 170 175 178 184 187 188
 190 191 192 195 271 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  11  12  13  14  15  17  18  19  23  26 166 167 170 175 176
 177 178 181 184 186 188 189 190 192 195 205 206 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  26 166 168 170 174 175 178 180 183
 184 188 190 192 195 268 374 408] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  21  26 166 170 173 175 178 179 182
 184 185 188 190 192 193 194 195 196 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  22  26 166 170 175 178 184 188 190
 192 195 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  26 166 169 170 175 178 184 187 188
 190 191 192 195 271 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  11  12  13  14  15  17  18  19  23  26 166 167 170 175 176
 177 178 181 184 186 188 189 190 192 195 205 206 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  26 166 168 170 174 175 178 180 183
 184 188 190 192 195 268 374 408] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  21  26 166 170 173 175 178 179 182
 184 185 188 190 192 193 194 195 196 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  22  26 166 170 175 178 184 188 190
 192 195 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw

/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  26 166 169 170 175 178 184 187 188
 190 191 192 195 271 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  11  12  13  14  15  17  18  19  23  26 166 167 170 175 176
 177 178 181 184 186 188 189 190 192 195 205 206 374] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [  8   9  10  12  13  14  15  18  19  26 166 168 170 174 175 178 180 183
 184 188 190 192 195 268 374 408] are constant.
  UserWarning)
/home/mishraka/anaconda3/lib/python3.7/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw

KeyboardInterrupt:

In [166]:
validation_score = gs.best_score_
print()
print('Cross-Validation Score:', -validation_score)
print()
print('Best parameters:', gs.best_params_)
print()

AttributeError: 'GridSearchCV' object has no attribute 'best_score_'

In [233]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from scipy.cluster import hierarchy as hc

In [335]:
m = RandomForestClassifier(n_estimators=200,min_samples_leaf=3 ,n_jobs=-1,max_features=0.3)
%time m.fit(X_train, y_train)
y_pred= m.predict(X_test)
accuracy_score(y_test, y_pred)

CPU times: user 1min 12s, sys: 72 ms, total: 1min 13s
Wall time: 10.7 s

0.8071380471380472

In [336]:
y_pred= m.predict(X_test_main_cleaned)

In [337]:
X_test_main_cleaned.shape, y_pred.shape

((14358, 95), (14358,))

In [338]:
submission_six_file = pd.DataFrame(X_test_main_cleaned.id.values, columns=['id'])

In [339]:
y = pd.DataFrame(y_pred, columns=['status_group'])

In [341]:
submission_six = pd.concat([submission_six_file, y], axis=1)

In [342]:
submission_six.to_csv('/home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/kaggle_competition/submission_six.csv', index=False)

In [343]:
!kaggle competitions submit -c ds1-predictive-modeling-challenge -f /home/mishraka/Documents/Manjula/Lambda_School/Assignments/Unit_2/kaggle_competition/submission_fifth.csv -m "third submission command"

100%|█████████████████████████████████████████| 262k/262k [00:01<00:00, 191kB/s]
Successfully submitted to DS1 Predictive Modeling Challenge

##plot time

In [ ]:
import seaborn as sns
sns.countplot(x=df_train_labels)